import CliffordCSS.Normalizer.Sweep

/-!
# The single-qubit Clifford layer on an `n`-qubit register

This file is pure mathematics : it continues the formalisation of
Nielsen & Chuang **Theorem 10.6** (the converse — the normalizer `N(Gₙ)` is generated by
Hadamard/phase/CNOT gates, Exercise 10.40) toward the multi-qubit inductive synthesis (parts 2–3).

The per-wire atom `CliffordCircuit.onWire j C₀` (landed PR 8) runs one single-wire Clifford on a
single chosen wire. The Gottesman tableau sweep that synthesises a Clifford circuit realising a
normalizer's signed permutation begins by rotating *every* wire's Pauli letter simultaneously — a
**single-qubit layer**: one (independently chosen) single-wire Clifford applied to each wire at
once. This file provides that combinator and its clean characterisation, by concatenating the
per-wire `onWire` circuits over `List.finRange n`.

Every statement names only raw matrix / index data (`CliffordCSS.CliffordCircuit`,
`CliffordCSS.pauliString` indices `Fin n → Fin 4`).

## What is proved

* `CliffordCircuit.layerOn f L` — run the single-wire circuit `f i` on wire `i` for each `i` in a
  wire list `L` (folding the per-wire `onWire i (f i)` circuits). `CliffordCircuit.singleQubitLayer`
  is the whole-register instance `layerOn f (List.finRange n)`.

* `CliffordCircuit.singleQubitLayer_act` — **the layer acts wire-by-wire independently**:
  `(singleQubitLayer f).act g i = (f i).act (fun _ => g i) 0`. Each wire `i`'s output letter is
  `f i`'s single-wire action on `g`'s letter at wire `i`, unaffected by the other wires.

* `CliffordCircuit.singleQubitLayer_sign` — **its `±1` phase is the product of the per-wire
  phases**: `(singleQubitLayer f).sign g = ∏ i, (f i).sign (fun _ => g i)`.

* `exists_singleQubitLayer_act_diagX` — **step 1 of the sweep: rotate a Pauli string to all-`X`**.
  For any Pauli string `a`, a single-qubit layer sends it to the string carrying `X` on every wire
  of `a`'s support and `I` elsewhere (`act (singleQubitLayer f) a k = if a k = 0 then 0 else 1`).
  Because the witness is returned as the per-wire family `f`, the layer's effect on *every other*
  string is simultaneously available through `singleQubitLayer_act` — exactly what the multi-qubit
  induction needs to track a second generator's image while diagonalising the first.
-/

open Matrix

noncomputable section

namespace CliffordCSS

variable {n : ℕ}

namespace CliffordCircuit

/-! ### Running one single-qubit circuit per wire -/

/-- **Run the single-wire circuit `f i` on wire `i`, for every `i` in the wire list `L`.**
Concatenation (`++`) of the per-wire circuits `onWire i (f i)`; the whole-register layer is the
`L = List.finRange n` instance (`singleQubitLayer`). -/
def layerOn (f : Fin n → CliffordCircuit 1) : List (Fin n) → CliffordCircuit n
  | [] => []
  | i :: L => onWire i (f i) ++ layerOn f L

@[simp]
theorem layerOn_nil (f : Fin n → CliffordCircuit 1) : layerOn f [] = [] := rfl

theorem layerOn_cons (f : Fin n → CliffordCircuit 1) (i : Fin n) (L : List (Fin n)) :
    layerOn f (i :: L) = onWire i (f i) ++ layerOn f L := rfl

/-- **`layerOn f L` leaves every wire outside `L` untouched**: for `k ∉ L`,
`(layerOn f L).act g k = g k`. Each `onWire i (f i)` in the fold touches only wire `i ∈ L`. -/
theorem layerOn_act_of_not_mem (f : Fin n → CliffordCircuit 1) (g : Fin n → Fin 4) {k : Fin n} :
    ∀ {L : List (Fin n)}, k ∉ L → act (layerOn f L) g k = g k := by
  intro L hk
  induction L with
  | nil => rfl
  | cons i L ih =>
      rw [List.mem_cons, not_or] at hk
      rw [layerOn_cons, act_append, onWire_act_of_ne _ _ _ hk.1, ih hk.2]

/-- **On a wire `k ∈ L` (with `L` duplicate-free) the layer acts as `f k` on that wire's letter**:
`(layerOn f L).act g k = (f k).act (fun _ => g k) 0`. The `onWire k (f k)` factor supplies wire
`k`'s transformation, and every other factor (a distinct wire) leaves wire `k` fixed. -/
theorem layerOn_act_of_mem (f : Fin n → CliffordCircuit 1) (g : Fin n → Fin 4) {k : Fin n}
    {L : List (Fin n)} (hk : k ∈ L) (hL : L.Nodup) :
    act (layerOn f L) g k = act (f k) (fun _ => g k) 0 := by
  induction L with
  | nil => simp at hk
  | cons i L ih =>
      rw [List.nodup_cons] at hL
      rw [layerOn_cons, act_append]
      rcases List.mem_cons.1 hk with h | h
      · subst h
        rw [onWire_act, layerOn_act_of_not_mem f g hL.1]
      · rw [onWire_act_of_ne _ _ _ (by rintro rfl; exact hL.1 h), ih h hL.2]

/-- **The layer's `±1` phase is the product of the per-wire phases** (for a duplicate-free `L`):
`(layerOn f L).sign g = (L.map fun i => (f i).sign (fun _ => g i)).prod`. Each `onWire i (f i)`
contributes `(f i).sign` read at wire `i`'s letter (`onWire_sign`), and — the earlier factors acting
on distinct wires — that letter is still `g i` (`layerOn_act_of_not_mem`). -/
theorem layerOn_sign (f : Fin n → CliffordCircuit 1) (g : Fin n → Fin 4) {L : List (Fin n)}
    (hL : L.Nodup) : sign (layerOn f L) g = (L.map fun i => sign (f i) (fun _ => g i)).prod := by
  induction L with
  | nil => rfl
  | cons i L ih =>
      rw [List.nodup_cons] at hL
      rw [layerOn_cons, sign_append, onWire_sign, layerOn_act_of_not_mem f g hL.1, ih hL.2,
        List.map_cons, List.prod_cons]
      ring

/-! ### The whole-register single-qubit layer -/

/-- **The single-qubit layer**: apply the single-wire circuit `f i` to wire `i`, for every wire `i`
of the `n`-qubit register (`layerOn f (List.finRange n)`). The first move of the Exercise 10.40
tableau sweep — rotating each wire's Pauli letter independently. -/
def singleQubitLayer (f : Fin n → CliffordCircuit 1) : CliffordCircuit n :=
  layerOn f (List.finRange n)

/-- **The single-qubit layer acts wire-by-wire independently**:
`(singleQubitLayer f).act g i = (f i).act (fun _ => g i) 0`. Wire `i`'s output letter depends only
on `f i` and `g`'s letter at wire `i`. -/
theorem singleQubitLayer_act (f : Fin n → CliffordCircuit 1) (g : Fin n → Fin 4) (i : Fin n) :
    act (singleQubitLayer f) g i = act (f i) (fun _ => g i) 0 :=
  layerOn_act_of_mem f g (by simp) (List.nodup_finRange n)

/-- **The single-qubit layer's `±1` phase is the product of the per-wire phases**:
`(singleQubitLayer f).sign g = ∏ i, (f i).sign (fun _ => g i)`. -/
theorem singleQubitLayer_sign (f : Fin n → CliffordCircuit 1) (g : Fin n → Fin 4) :
    sign (singleQubitLayer f) g = ∏ i, sign (f i) (fun _ => g i) := by
  rw [singleQubitLayer, layerOn_sign f g (List.nodup_finRange n), ← List.ofFn_eq_map,
    List.prod_ofFn]

/-! ### Rotating a single Pauli letter to `X` -/

/-- **A single-wire Clifford rotating the letter `c` to `X`.** `X` needs no gate; `S` sends `Y ↦ X`
(`phasePauli`); `H` sends `Z ↦ X` (`hadamardPauli`). The identity `I` (`c = 0`) is left as `I`. -/
def rotateToX (c : Fin 4) : CliffordCircuit 1 :=
  if c = 2 then [CliffordGate.phase 0] else if c = 3 then [CliffordGate.had 0] else []

/-- **`rotateToX c` sends the letter `c` to `X`** (and fixes `I`): `(rotateToX c).act (fun _ => c) 0
= if c = 0 then 0 else 1`. Verified by cases on `c` (`decide` on the computable single-wire
action). -/
theorem rotateToX_act (c : Fin 4) :
    act (rotateToX c) (fun _ => c) 0 = if c = 0 then 0 else 1 := by
  fin_cases c <;> decide

end CliffordCircuit

/-! ### Step 1 of the sweep: diagonalise a Pauli string to all-`X` -/


end CliffordCSS

end
