import CliffordCSS.Normalizer.Basic
import CliffordCSS.Encoding.PhaseCZLayer

/-!
# Single-wire Clifford synthesis on any wire of an `n`-qubit register

This file is pure mathematics : it continues the formalisation of
Nielsen & Chuang **Theorem 10.6** (the converse — the normalizer `N(Gₙ)` is generated by
Hadamard/phase/CNOT gates, Exercise 10.40) toward the multi-qubit inductive synthesis (parts 2–3).

The landed base case (`isPauliNormalizer_singleQubit_eq_smul_cliffordCircuit`) synthesises a
Clifford circuit realising an arbitrary valid single-qubit signed permutation — but only on the
*single-wire*
register `Fin 1`. The multi-qubit induction sweeps qubit by qubit, and to do so needs to run *any*
single-qubit Clifford on *any chosen wire* of the full register while leaving every other wire
undisturbed. This file provides exactly that atom, by transporting the `Fin 1` synthesis onto a
chosen wire through the wire-relabeling machinery of `CliffordCSS/Pauli/CliffordCircuit.lean`
(landed PR 6).

Every statement names only raw matrix / index data (`CliffordCSS.CliffordCircuit`,
`CliffordCSS.pauliString` indices `Fin n → Fin 4`, `CliffordCSS.xGenPauli`/`zGenPauli`).

## What is proved

* `wireEmbedding` — the wire-selecting embedding `Fin 1 ↪ Fin n` picking out a single wire `j`
  (injective vacuously, as `Fin 1` is a subsingleton). This is the `f = fun _ => j` instance of the
  embedding that `CliffordCircuit.relabel` transports a circuit along.

* `CliffordCircuit.onWire j C₀` — the `n`-wire circuit that runs the single-wire circuit `C₀` on
  wire `j` (`relabel (wireEmbedding j) C₀`).

* `CliffordCircuit.onWire_act` / `onWire_act_of_ne` / `onWire_sign` — the **characterisation of
  `onWire`'s action and phase on the whole register**: on wire `j` the phase-free action is `C₀`'s
  single-wire action read off wire `j`'s letter (`onWire_act`), every wire `k ≠ j` is left untouched
  (`onWire_act_of_ne`), and the `±1` phase is `C₀`'s phase at wire `j`'s letter (`onWire_sign`).
  These are the direct specialisations of `act_relabel_embed`, `act_relabel_of_forall_ne` and
  `sign_relabel` to the single-wire embedding.

* `exists_cliffordCircuit_onWire_act_sign` — **single-wire signed-permutation synthesis on an
  arbitrary wire.** For any wire `j`, distinct non-identity target letters `aX, aZ` and signs
  `zX, zZ ∈ {±1}`, there is an `n`-wire Clifford circuit realising, on wire `j`, the signed
  permutation `Xⱼ ↦ zX · (aX on wire j)`, `Zⱼ ↦ zZ · (aZ on wire j)` exactly, while fixing every
  other wire. This is the multi-qubit lift of `exists_cliffordCircuit_singleQubit_act_sign`, the
  per-wire building block of the Exercise 10.40 sweep.
-/

open Matrix

noncomputable section

namespace CliffordCSS

variable {n : ℕ}

/-! ### The single-wire embedding -/

/-- **The wire-selecting embedding `Fin 1 ↪ Fin n`** picking out a single wire `j`: the constant map
`fun _ => j`, injective because `Fin 1` is a subsingleton. `CliffordCircuit.relabel` transports a
single-wire circuit onto wire `j` of the `n`-wire register along this embedding. -/
def wireEmbedding (j : Fin n) : Fin 1 ↪ Fin n :=
  ⟨fun _ => j, fun _ _ _ => Subsingleton.elim _ _⟩

@[simp]
theorem wireEmbedding_apply (j : Fin n) (i : Fin 1) : wireEmbedding j i = j := rfl

namespace CliffordCircuit

/-! ### Running a single-wire circuit on a chosen wire -/

/-- **Run the single-wire circuit `C₀` on wire `j`** of the `n`-wire register: relabel each gate's
wire to `j` (`relabel (wireEmbedding j) C₀`). The result is a genuine `n`-wire Clifford circuit
touching only wire `j`. -/
def onWire (j : Fin n) (C₀ : CliffordCircuit 1) : CliffordCircuit n :=
  relabel (wireEmbedding j) C₀

/-- **On wire `j`, `onWire j C₀` acts as `C₀` on wire `j`'s letter**:
`(onWire j C₀).act g j = C₀.act (fun _ => g j) 0`. Immediate from `act_relabel_embed` at index `0`
of the single-wire embedding. -/
theorem onWire_act (j : Fin n) (C₀ : CliffordCircuit 1) (g : Fin n → Fin 4) :
    act (onWire j C₀) g j = act C₀ (fun _ => g j) 0 := by
  have h := act_relabel_embed (wireEmbedding j) C₀ g 0
  simpa only [onWire, wireEmbedding_apply] using h

/-- **`onWire j C₀` leaves every wire `k ≠ j` untouched**: `(onWire j C₀).act g k = g k`. Immediate
from `act_relabel_of_forall_ne` (every embedded wire is `j ≠ k`). -/
theorem onWire_act_of_ne (j : Fin n) (C₀ : CliffordCircuit 1) (g : Fin n → Fin 4) {k : Fin n}
    (hk : k ≠ j) : act (onWire j C₀) g k = g k :=
  act_relabel_of_forall_ne (wireEmbedding j) C₀ g (fun i => by simpa using hk.symm)

/-- **The `±1` phase of `onWire j C₀` is `C₀`'s phase at wire `j`'s letter**:
`(onWire j C₀).sign g = C₀.sign (fun _ => g j)`. Immediate from `sign_relabel`. -/
theorem onWire_sign (j : Fin n) (C₀ : CliffordCircuit 1) (g : Fin n → Fin 4) :
    sign (onWire j C₀) g = sign C₀ (fun _ => g j) := by
  have h := sign_relabel (wireEmbedding j) C₀ g
  simpa only [onWire, wireEmbedding_apply] using h

/-- **`onWire j C₀` runs `C₀`'s single-qubit action on a single-wire Pauli.** For a string carrying
letter `c` on wire `j` and identity elsewhere (`Function.update 0 j c`),
`(onWire j C₀).act (Function.update 0 j c) = Function.update 0 j (C₀.act (fun _ => c) 0)` — the
image is again supported on wire `j`, carrying the letter `C₀` sends `c` to. From `onWire_act` on
wire `j` and `onWire_act_of_ne` off it — the form the multi-qubit synthesis applies to the
generators `Xⱼ = update 0 j 1` and `Zⱼ = update 0 j 3`. -/
theorem onWire_act_update (j : Fin n) (C₀ : CliffordCircuit 1) (c : Fin 4) :
    act (onWire j C₀) (Function.update (0 : Fin n → Fin 4) j c)
      = Function.update (0 : Fin n → Fin 4) j (act C₀ (fun _ => c) 0) := by
  funext k
  rcases eq_or_ne k j with hk | hk
  · subst hk
    rw [onWire_act, Function.update_self, Function.update_self]
  · rw [onWire_act_of_ne _ _ _ hk, Function.update_of_ne hk, Function.update_of_ne hk]

end CliffordCircuit

/-! ### Single-wire signed-permutation synthesis on an arbitrary wire -/


end CliffordCSS

end
