import CliffordCSS.Normalizer.ZClear

/-!
# The Clifford action is symplectic — the first move of the pair reduction

This file is pure mathematics : it continues the formalisation of
Nielsen & Chuang **Theorem 10.6** (the converse — the normalizer `N(Gₙ)` is generated by
Hadamard/phase/CNOT gates, Exercise 10.40) toward the multi-qubit inductive synthesis (parts 2–3),
by establishing the *symplectic structure* of a Clifford circuit's action on Pauli strings.

The single-generator reduction `exists_cliffordCircuit_reduceToXGen`/`…ToZGen` (PR 12) collapses one
generator image `U X₁ U†` to a standard `X_c`/`Z_c`. The Exercise 10.40 first-qubit reduction must
reduce the *anticommuting pair* `U X₁ U†`, `U Z₁ U†` *simultaneously*, to `X_c` and `Z_c` on a
**common** wire. The key structural fact making this possible is that a Clifford circuit's action
preserves commutation — precisely how N&C open part 2: "since `Z₁` and `X₁` anticommute, `U Z₁ U†`
and `U X₁ U†` anticommute". This file records that invariant at the circuit level and derives the
symplectic *first move* of the pair reduction.

## Deliverables

* `CliffordCircuit.act_pauliAnticommCount_even_iff` — **the Clifford action is symplectic**: for any
  circuit `C`, `Even (pauliAnticommCount (act C g) (act C h)) ↔ Even (pauliAnticommCount g h)`. A
  Clifford circuit's phase-free action on the check matrix preserves the mod-2 symplectic form of
  Exercise 10.33. The circuit-level counterpart of the normalizer-level
  `IsPauliNormalizer.exists_signedPerm_symplectic` (PR 5), proved the same way: `act C` corresponds
  to conjugation by the unitary `toMatrix C` (`conj_pauliString`), conjugation preserves commutation
  (`unitaryConj_commute_iff`), and `pauliString_commute_iff` (Ex 10.33) turns commutation into the
  parity statement.
* `pauliAnticommCount_xGenPauli` / `…_zGenPauli` — **single-generator positions**: the symplectic
  pairing of a string `h` against a standard generator is a single check bit,
  `pauliAnticommCount h (xGenPauli c) = pauliZBit (h c)` and
  `pauliAnticommCount h (zGenPauli c) = pauliXBit (h c)`.
* `odd_pauliAnticommCount_xGenPauli_iff` / `…_zGenPauli_iff` — the parity reading: `h` anticommutes
  with `X_c` iff its `c`-letter has a `Z` factor (`h c ∈ {Y, Z}`), and with `Z_c` iff it has an `X`
  factor (`h c ∈ {X, Y}`).
* `exists_cliffordCircuit_reduceFirstOfPair` — **the symplectic first move of the pair reduction**:
  for anticommuting `p, q` (`Odd (pauliAnticommCount p q)`) there is a Clifford circuit `C` and a
  pivot wire `c` reducing `p` to the standard `X_c` exactly (`act C p = xGenPauli c`,
  `sign C p = 1`) such that the partner image `act C q` *still anticommutes with `X_c`* — concretely
  `act C q c ∈ {Y, Z}`. This is the starting configuration a later PR completes by reducing
  `act C q` to `Z_c` while fixing `X_c`.

Every statement names only raw matrix / index data (`CliffordCSS.CliffordCircuit`,
`CliffordCSS.pauliString` indices `Fin n → Fin 4`, `CliffordCSS.xGenPauli`/`zGenPauli`,
`CliffordCSS.pauliAnticommCount`).
-/

open Matrix

noncomputable section

namespace CliffordCSS

variable {n : ℕ}

namespace CliffordCircuit

/-- **The Clifford action is symplectic.** A Clifford circuit's phase-free action on Pauli strings
preserves the mod-2 symplectic form of Nielsen & Chuang Exercise 10.33: for any circuit `C` and
Pauli strings `g, h`, `Even (pauliAnticommCount (act C g) (act C h)) ↔ Even (pauliAnticommCount g
h)`.

This is the circuit-level counterpart of the normalizer-level
`IsPauliNormalizer.exists_signedPerm_symplectic` (PR 5), and is proved the same way: `act C`
corresponds to conjugation by the unitary `toMatrix C`
(`conj_pauliString`: `toMatrix C · P_g · (toMatrix C)ᴴ = sign C g • P_{act C g}`), conjugation by a
unitary preserves commutation (`unitaryConj_commute_iff`) — the `±1` phases `sign C g` cancel — and
`pauliString_commute_iff` translates commutation into the parity statement both ways. It is the
structural invariant the inductive synthesis of Exercise 10.40 must reproduce: a Clifford circuit
maps anticommuting Pauli strings to anticommuting ones. -/
theorem act_pauliAnticommCount_even_iff (C : CliffordCircuit n) (g h : Fin n → Fin 4) :
    Even (pauliAnticommCount (act C g) (act C h)) ↔ Even (pauliAnticommCount g h) := by
  rw [← pauliString_commute_iff, ← pauliString_commute_iff]
  have hUmem : toMatrix C ∈ Matrix.unitaryGroup (Fin n → Fin 2) ℂ := by
    rw [mem_unitaryGroup_iff, star_eq_conjTranspose]; exact mul_conjTranspose C
  -- the `±1` conjugation phases cancel, so the images commute iff the raw conjugates do
  have hstep : Commute (toMatrix C * pauliString g * (toMatrix C)ᴴ)
      (toMatrix C * pauliString h * (toMatrix C)ᴴ)
      ↔ Commute (pauliString (act C g)) (pauliString (act C h)) := by
    rw [conj_pauliString C g, conj_pauliString C h,
      Commute.smul_left_iff₀ (sign_ne_zero C g), Commute.smul_right_iff₀ (sign_ne_zero C h)]
  exact hstep.symm.trans (unitaryConj_commute_iff hUmem (pauliString g) (pauliString h))

end CliffordCircuit

/-! ### Single-generator positions: the symplectic pairing against a standard generator -/


/-! ### The symplectic first move of the pair reduction -/


end CliffordCSS

end
