import CliffordCSS.Normalizer.Layer

/-!
# The `Z`-generator sweep — diagonalise to all-`Z` and collapse to a single `Z`

This file is pure mathematics : it continues the formalisation of
Nielsen & Chuang **Theorem 10.6** (the converse — the normalizer `N(Gₙ)` is generated by
Hadamard/phase/CNOT gates, Exercise 10.40) toward the multi-qubit inductive synthesis (parts 2–3).

It is the **`Z`-generator companion** of the `X`-generator sweep already landed:

* diagonalise-to-all-`X` (`exists_singleQubitLayer_act_diagX`, PR 9) and
* CNOT-clear-to-single-`X` (`exists_cliffordCircuit_cnotClear_toSingleX`, PR 10).

The Gottesman tableau sweep reduces a normalizer's action on the second generator `U Z₁ U†` by the
mirror-image of the first-generator moves, working in the `Z` (rather than `X`) basis:

1. **Diagonalise to all-`Z`** (*this file*, `exists_singleQubitLayer_act_diagZ`): a single-qubit
   layer rotates the image to a string carrying `Z` on its support and `I` elsewhere. The per-wire
   rotation `rotateToZ` uses `H` (`X ↦ Z`) and `H S` (`Y ↦ X ↦ Z`); `Z` and `I` need no gate.
2. **Collapse to a single generator** (*this file*, `exists_cliffordCircuit_cnotClear_toSingleZ`): a
   **fan of CNOTs into** one support wire `c` (that wire the common *target*, every other support
   wire a *control*) clears the `Z` off every other support wire, leaving `Z` on wire `c` alone
   (`zGenPauli c`).

The clearing move is the `Z`-basis mirror of the `X`-clearing of PR 10. For `X` a single
`CNOT_{c→t}` (control `c`, target `t`) copies the control's `X` onto the target (`x_t += x_c`,
Figure 10.7), so a fan *out of* `c` clears an all-`X` string down to `X_c`. For `Z` the propagation
runs the other way — `CNOT_{t→c}` sends the target's `Z` onto the control (`z_c += z_t`), i.e. a
`CNOT` whose **control** is `t` and **target** is `c` clears `Z` off `t` (`cnotCtrlPauli 3 3 = 0`)
while keeping `Z` on `c` (`cnotTgtPauli 3 3 = 3`). So the `Z`-collapse fan reverses the control/
target roles of the `X`-collapse fan: `cnotFanInto c ts` runs `CNOT_{t→c}` for each `t ∈ ts`.

Every statement names only raw matrix / index data (`CliffordCSS.CliffordCircuit`,
`CliffordCSS.pauliString` indices `Fin n → Fin 4`, `CliffordCSS.zGenPauli`).

## What is proved

* `CliffordCircuit.rotateToZ` / `rotateToZ_act` — a single-wire Clifford rotating a Pauli letter to
  `Z` (fixing `I`): `H` for `X`, `H S` for `Y`.
* `exists_singleQubitLayer_act_diagZ` — **sweep step 1 (`Z` basis)**: a single-qubit layer sends any
  Pauli string to its all-`Z`-on-support form, returned as the per-wire family so the layer's action
  on any other string stays available through `CliffordCircuit.singleQubitLayer_act`.
* `cnotFanInto` — the **reverse CNOT fan**: `CNOT_{t→c}` for every `t ∈ ts` (targets folded into the
  single control-collector wire `c`). `act_cnotFanInto_collapse` gives its clearing action on an
  all-`Z` string and `sign_cnotFanInto_collapse` its trivial `±1` phase.
* `exists_cliffordCircuit_cnotClear_toSingleZ` — **sweep step 2 (`Z` basis, the deliverable)**: for
  any all-`Z` string `a` with a pivot `c` in its support, a Clifford circuit realising
  `a ↦ zGenPauli c` exactly, with phase `1`. Together with the diagonalisation step this reduces a
  normalizer's second generator image `U Z₁ U†` to the standard `Z₁`, the `Z`-basis mirror of the
  `X`-generator reduction of PRs 9–10.
-/

open Matrix

noncomputable section

namespace CliffordCSS

variable {n : ℕ}

namespace CliffordCircuit

/-! ### Rotating a single Pauli letter to `Z` -/

/-- **A single-wire Clifford rotating the letter `c` to `Z`.** `Z` needs no gate; `H` sends
`X ↦ Z` (`hadamardPauli`); `H S` sends `Y ↦ X ↦ Z` (`S` first, `phasePauli 2 = 1`; then `H`,
`hadamardPauli 1 = 3`). The identity `I` (`c = 0`) is left as `I`. -/
def rotateToZ (c : Fin 4) : CliffordCircuit 1 :=
  if c = 1 then [CliffordGate.had 0]
  else if c = 2 then [CliffordGate.had 0, CliffordGate.phase 0] else []

/-- **`rotateToZ c` sends the letter `c` to `Z`** (and fixes `I`): `(rotateToZ c).act (fun _ => c) 0
= if c = 0 then 0 else 3`. Verified by cases on `c` (`decide` on the computable single-wire
action; the two-gate `Y` case composes right-to-left, `S` then `H`). -/
theorem rotateToZ_act (c : Fin 4) :
    act (rotateToZ c) (fun _ => c) 0 = if c = 0 then 0 else 3 := by
  fin_cases c <;> decide

end CliffordCircuit

/-! ### Sweep step 1 (`Z` basis): diagonalise a Pauli string to all-`Z` -/


/-! ### The reverse CNOT fan: collapsing an all-`Z` string -/

/-- **The reverse CNOT fan into a collector wire `c`.** Runs `CNOT_{t→c}` (control `t`, target `c`)
for each `t ∈ ts` (`ts.flatMap (fun t => cnotStep t c)`). This is the control/target mirror of
`cnotFan` (which fixes a single control and fans onto many targets): here a single target `c`
collects from many controls, so that a fan of `Z`-carrying controls collapses onto the single
target `c` (`z_c += z_t` clears the control's `Z`, keeps the target's). -/
def cnotFanInto (c : Fin n) (ts : List (Fin n)) : CliffordCircuit n :=
  ts.flatMap (fun t => cnotStep t c)

@[simp]
theorem cnotFanInto_nil (c : Fin n) : cnotFanInto c [] = [] := rfl


/-! ### Sweep step 2 (`Z` basis): collapse an all-`Z` image to a single `Z` generator -/


end CliffordCSS

end
