import CliffordCSS.Symplectic.CheckMatrix
import Mathlib.Algebra.Field.ZMod
import Mathlib.LinearAlgebra.BilinearForm.Properties
import Mathlib.LinearAlgebra.Matrix.BilinearForm
import Mathlib.LinearAlgebra.Basis.VectorSpace

/-!
# Nielsen & Chuang Proposition 10.4 — flipping a single stabilizer generator

This file is pure mathematics : it formalizes Nielsen & Chuang's
**Proposition 10.4** (§10.5.1, p. 458), the "innocuous looking" but repeatedly-used fact behind
the dimension count for stabilizer code spaces (Proposition 10.5) and the manipulation of
stabilizers under Clifford gates.

> **Proposition 10.4.** Let `S = ⟨g₁, …, g_l⟩` be generated by `l` independent generators and
> satisfy `-I ∉ S`. Fix `i` in the range `1, …, l`. Then there exists `g ∈ Gₙ` such that
> `g gᵢ g† = -gᵢ` and `g gⱼ g† = gⱼ` for all `j ≠ i`.
> — Nielsen & Chuang, *Quantum Computation and Quantum Information*, Proposition 10.4 (p. 458).

## Statement shape and faithfulness

We work throughout with the **phase-free** Pauli strings `CliffordCSS.pauliString g` (indexed by
`g : Fin n → Fin 4`), which carry no `±1, ±i` prefactor. Two design points make this faithful to
N&C:

* **`-I ∉ S` enters only through `gⱼ² = I`.** N&C's hypothesis `-I ∉ S` forces every element of `S`
  — in particular every generator — to square to the identity and hence to be a *Hermitian
  involution* (Exercises 10.34/10.35). That per-generator involution property is all the proof of
  10.4 actually uses, and every `pauliString g` is already an involution (`pauliString_mul_self`)
  and Hermitian (`pauliString_isHermitian`) unconditionally. So the phase-free representation
  supplies exactly the consequence of `-I ∉ S` the argument needs — with no `-I ∉ S` hypothesis to
  carry. (It does *not* claim the phase-free strings generate a group avoiding `-I`; e.g.
  `(P_X P_Z)² = -I`. The proof never needs that group-level fact.)
* **"independent generators" ⇔ "check-matrix rows linearly independent".** This is exactly the
  content of Proposition 10.3 (in the `-I ∉ S` world). N&C's proof of 10.4 opens by invoking 10.3
  to pass to linear independence of the rows, and the whole argument then uses only that. We
  therefore state the hypothesis directly as `LinearIndependent (ZMod 2) (fun j ↦ checkRow (gⱼ))`
  — the equivalent (not weaker) form the proof consumes. The check row `checkRow`
  (`CliffordCSS/Symplectic/CheckMatrix.lean`) is the `(x | z)` symplectic representation.

The conjugation `g gⱼ g†` is `pauliString p * pauliString (gⱼ) * star (pauliString p)`, with
`star` the Hermitian adjoint (`†`); a phase-free Pauli string is Hermitian, so `star (pauliString
p) = pauliString p`, but writing the adjoint keeps the statement literally N&C's `g gⱼ g†`.

## The proof

Conjugation by a Pauli string reads off the commutation sign (`pauliString_conj`):
`P_p P_h P_p† = (-1)^{⟨p, h⟩} P_h`, where `⟨p, h⟩ = pauliAnticommCount p h` is the symplectic form
of Exercise 10.33. So the task is to find `p` whose symplectic form with `gⱼ` has parity `δᵢⱼ`.

This is the linear-algebra heart of N&C's proof ("`GΛx = eᵢ` has a solution because the rows of
`G` are independent"). We realize it over the field `ZMod 2`:

* `checkSymplectic` is the binary symplectic form `⟨(x, z), (x', z')⟩ = ∑ₖ (xₖ z'ₖ + zₖ x'ₖ)` on
  check rows; `checkSymplectic_checkRow` identifies it with `(pauliAnticommCount g h : ZMod 2)`.
* `checkSymplectic_nondegenerate`: the form is nondegenerate.
* Since the rows `checkRow (gⱼ)` are linearly independent, `checkRow (gᵢ)` is not in the span of the
  others (`LinearIndependent.notMem_span`), so there is a *separating functional* `f`
  (`Submodule.exists_le_ker_of_notMem`) with `f (checkRow gᵢ) ≠ 0` and `f` vanishing on the others.
  Over `ZMod 2` "nonzero" means "`= 1`", so `f (checkRow gⱼ) = δᵢⱼ`.
* Nondegeneracy makes `checkSymplectic` a linear equivalence to the dual
  (`LinearMap.BilinForm.toDual`), so `f = checkSymplectic w` for some `w`; and `checkRow` is onto
  (`checkRow_surjective`), so `w = checkRow p` for a Pauli index `p`. Then
  `(pauliAnticommCount p gⱼ : ZMod 2) = f (checkRow gⱼ) = δᵢⱼ`, i.e. the count is odd exactly for
  `j = i`, giving `P_p P_{gᵢ} P_p† = -P_{gᵢ}` and `P_p P_{gⱼ} P_p† = P_{gⱼ}` for `j ≠ i`.

Everything names only raw matrix / index data (`Matrix`, `CliffordCSS.pauliString`, `ZMod 2`,
`Fin n → Fin 4`). The reusable pieces (`pauliString_conj`, `checkSymplectic` and its
nondegeneracy, `checkRow_surjective`) are shared infrastructure for the rest of the Chapter 10
stabilizer program (Proposition 10.5, Theorems 10.6–10.8).

N&C Proposition 10.4, p. 458.
-/

open Matrix

open scoped BigOperators

namespace CliffordCSS

variable {n : ℕ}

/-! ### Conjugation of a Pauli string by another -/


/-! ### The binary symplectic form on check rows -/

/-- The **binary symplectic form** on check-matrix rows, `⟨(x, z), (x', z')⟩ = ∑ₖ (xₖ z'ₖ + zₖ
x'ₖ)` over `ZMod 2`. This is `r(g) Λ r(g')ᵀ` for `Λ = [[0, I], [I, 0]]`; it is the mod-2 quantity
of Nielsen & Chuang, Exercise 10.33, packaged as an honest `ZMod 2`-bilinear form so that its
nondegeneracy is available for the linear algebra of Proposition 10.4. -/
def checkSymplectic :
    LinearMap.BilinForm (ZMod 2) ((Fin n → ZMod 2) × (Fin n → ZMod 2)) :=
  LinearMap.mk₂ (ZMod 2)
    (fun u v => ∑ k, (u.1 k * v.2 k + u.2 k * v.1 k))
    (fun u₁ u₂ v => by
      rw [← Finset.sum_add_distrib]
      refine Finset.sum_congr rfl fun k _ => ?_
      simp only [Prod.fst_add, Prod.snd_add, Pi.add_apply]; ring)
    (fun c u v => by
      rw [Finset.smul_sum]
      refine Finset.sum_congr rfl fun k _ => ?_
      simp only [Prod.smul_fst, Prod.smul_snd, Pi.smul_apply, smul_eq_mul]; ring)
    (fun u v₁ v₂ => by
      rw [← Finset.sum_add_distrib]
      refine Finset.sum_congr rfl fun k _ => ?_
      simp only [Prod.fst_add, Prod.snd_add, Pi.add_apply]; ring)
    (fun c u v => by
      rw [Finset.smul_sum]
      refine Finset.sum_congr rfl fun k _ => ?_
      simp only [Prod.smul_fst, Prod.smul_snd, Pi.smul_apply, smul_eq_mul]; ring)

@[simp]
theorem checkSymplectic_apply (u v : (Fin n → ZMod 2) × (Fin n → ZMod 2)) :
    checkSymplectic u v = ∑ k, (u.1 k * v.2 k + u.2 k * v.1 k) := by
  simp only [checkSymplectic, LinearMap.mk₂_apply]

/-- The symplectic form on check rows **is** the mod-2 anticommutation count:
`checkSymplectic (r g) (r h) = (pauliAnticommCount g h : ZMod 2)`. Both sides are the sum over
qubits of `x_g z_h + z_g x_h`; the left computes it in `ZMod 2`, the right casts the `ℕ`-valued
`pauliAnticommCount` (a sum of `singlePauliAnticomm`s). -/
theorem checkSymplectic_checkRow (g h : Fin n → Fin 4) :
    checkSymplectic (checkRow g) (checkRow h) = (pauliAnticommCount g h : ZMod 2) := by
  rw [checkSymplectic_apply, pauliAnticommCount, Nat.cast_sum]
  refine Finset.sum_congr rfl fun k _ => ?_
  simp only [checkRow, pauliBit, singlePauliAnticomm]
  push_cast
  ring


/-! ### Surjectivity of the check-row map -/

/-- The inverse of the single-qubit check-bit map `pauliBit`: the Pauli index with prescribed
`(x, z)` bits (`(0,0) ↦ I`, `(1,0) ↦ X`, `(1,1) ↦ Y`, `(0,1) ↦ Z`). Used to invert `checkRow`
qubitwise. -/
def bitToPauli (b : ZMod 2 × ZMod 2) : Fin 4 :=
  if b.1 = 0 then (if b.2 = 0 then 0 else 3) else (if b.2 = 0 then 1 else 2)

/-- `bitToPauli` is a right inverse of `pauliBit`: `pauliBit (bitToPauli b) = b`. A finite check on
the four `(x, z)` bit patterns. -/
theorem pauliBit_bitToPauli : ∀ b : ZMod 2 × ZMod 2, pauliBit (bitToPauli b) = b := by decide

/-- `bitToPauli` is also a **left** inverse of `pauliBit`: `bitToPauli (pauliBit a) = a`. With
`pauliBit_bitToPauli` this makes `pauliBit` a bijection `Fin 4 ≃ ZMod 2 × ZMod 2` — the faithfulness
of the `(x | z)` representation on a single qubit. A four-case check. -/
theorem bitToPauli_pauliBit (a : Fin 4) : bitToPauli (pauliBit a) = a := by decide +revert

/-- **The single-qubit label inverse is multiplicative**: `bitToPauli (b + c) =
bitToPauli b ⊙ bitToPauli c`. The inverse form of `pauliBit_pauliMul` — adding `(x | z)` bits mod 2
corresponds to multiplying Paulis (up to phase). A `16`-case check. -/
theorem bitToPauli_add (b c : ZMod 2 × ZMod 2) :
    bitToPauli (b + c) = pauliMul (bitToPauli b) (bitToPauli c) := by decide +revert


/-! ### Proposition 10.4 -/


end CliffordCSS
