import CliffordCSS.DepthOne.LogicalAction
import CliffordCSS.DepthOne.Theorem

/-!
# The Corollary (Depth-one logical generation), Appendix D

Pure mathematics . This file proves the **Corollary** of
*Beyond transversality* (arXiv:2608.05688, App. D, `cor-depthone`, Eq. `d1-log`): the logical
image of the depth-one group is generated by the logical images of the three depth-one families,
taken over all matchings.

## The objects

* `depthOneGroup C_X C_Z` — the paper's `N_dep`: the join, in the ambient subgroup lattice of
  `Sp(2n, 𝔽₂)`, of the fixed-matching slices `N_M` over **all** matchings `M` (an involution
  `σ`, `σ² = 1`). This is the depth-one group of the paper's chain `N_tr ≤ N_M ≤ N_dep ≤ N_full`.
* `logicalActionHom` — the paper's logical action `λ : N_full ↠ Sp(2k)`.

## The Corollary (`logicalAction_depthOneGroup_eq`)

For an isotropic label space `𝒞` — the paper's standing hypothesis "Let `𝒞` in addition be
isotropic, so that `λ : N_full ↠ Sp(2k)` is defined" — the logical image of `N_dep` is
`λ(N_dep) = ⟨ ⋃_M λ(S^Z_M ∪ S^X_M ∪ L_M) ⟩`, the union over all matchings. In the subgroup
lattice this is the join `⨆_M (λ(S^Z_M) ⊔ λ(S^X_M) ⊔ λ(L_M))`: for a family of subgroups,
`⟨ ⋃_M X_M ⟩` **is** `⨆_M ⟨X_M⟩` (`Subgroup.iSup_eq_closure`), and the image of a subgroup under a
homomorphism is a subgroup, so `⟨λ(S^Z_M) ∪ λ(S^X_M) ∪ λ(L_M)⟩ = λ(S^Z_M) ⊔ λ(S^X_M) ⊔ λ(L_M)`.
The `⨆`/`⊔` form is therefore the faithful lattice rendering of the paper's generated-subgroup
notation, and is what `Subgroup.map_iSup`/`Subgroup.map_sup` operate on.

## The proof (the paper's, verbatim — "Passing to logical actions needs no new argument")

`λ` is a homomorphism, so `λ(N_dep) = λ(⨆_M N_M) = ⨆_M λ(N_M)` (`Subgroup.map_iSup`). It is thus
enough to treat one slice `N_M` at a time. By **Theorem D.1** `N_M = S^Z_M ⊔ S^X_M ⊔ L_M`, and a
homomorphism maps a join
of subgroups to the join of the images (`Subgroup.map_sup`), so
`λ(N_M) = λ(S^Z_M) ⊔ λ(S^X_M) ⊔ λ(L_M)`. Taking the union over all matchings gives the result.

## A note on the isotropy hypothesis

`_hiso : IsIsotropic (cssLabelSpaceSum C_X C_Z)` is the paper's standing assumption for the
Corollary ("Let `𝒞` in addition be isotropic, so that `λ : N_full ↠ Sp(2k)` is defined"): isotropy
is what makes `λ`'s codomain `logicalSymplecticGroup` the paper's `Sp(2k)` of dimension `2k`
(`finrank_logicalSpace_add_two_mul`). The generation **equation** itself — an equality of image
subgroups — holds for *any* label space, because `λ` is a homomorphism regardless of isotropy; the
proof therefore does not consume `_hiso` (its `_`-prefix records that it is deliberately unused). It
is kept in the statement so the Corollary is stated at exactly the paper's scope (with `Sp(2k)`
genuinely the paper's `Sp(2k)`), never weakened and never silently generalized away from the printed
hypothesis.

All is `𝔽₂`-symplectic linear algebra naming only the raw carrier `Matrix`/`ZMod`/`Submodule`. No
`sorry`, no new `axiom`, no `native_decide`. Surjectivity of `λ` (the paper's `↠`) is **not** used:
the Corollary consumes only the homomorphism property. -/

open Matrix

namespace CliffordCSS

variable {ι : Type*} [Fintype ι] [DecidableEq ι]
variable {C_X C_Z : Submodule (ZMod 2) (ι → ZMod 2)}

/-- **The depth-one group `N_dep`** (*Beyond transversality*, App. D): the join, in the ambient
subgroup lattice of `Sp(2n, 𝔽₂)`, of the fixed-matching slices `N_M = fixedMatchingSlice C_X C_Z σ`
over **all** matchings `M` — encoded as involutions `σ` (`σ² = 1`, Convention c3). It sits in the
paper's chain `N_tr ≤ N_M ≤ N_dep ≤ N_full`: modulo Pauli operators, the code-preserving actions
reachable by a finite-depth circuit whose every layer is `2`-local. -/
def depthOneGroup (C_X C_Z : Submodule (ZMod 2) (ι → ZMod 2)) :
    Subgroup ↥(binarySymplecticGroup ι) :=
  ⨆ σ : {σ : Equiv.Perm ι // Function.Involutive σ}, fixedMatchingSlice C_X C_Z σ.1 σ.2

/-- `N_dep ≤ N_full`: the depth-one group lies in the code-preserving group, since each slice
`N_M ≤ N_full` (`fixedMatchingSlice_le_codePreservingGroup`). This is the top of the paper's chain
`N_tr ≤ N_M ≤ N_dep ≤ N_full`. -/
theorem depthOneGroup_le_codePreservingGroup :
    depthOneGroup C_X C_Z ≤ codePreservingGroup C_X C_Z :=
  iSup_le fun σ => fixedMatchingSlice_le_codePreservingGroup C_X C_Z σ.1 σ.2

/-- Restricting `N_dep` to a subgroup of `N_full` commutes with the join over matchings:
`(N_dep).subgroupOf N_full = ⨆_M (N_M).subgroupOf N_full`. This holds because every slice
`N_M ≤ N_full`, so applying the injective `Subgroup.map N_full.subtype` to both sides collapses each
`· ⊓ N_full` (`Subgroup.subgroupOf_map_subtype`) and both reduce to `⨆_M N_M = N_dep`. (In general
`subgroupOf = comap` does not distribute over `⨆`; the hypothesis `N_M ≤ N_full` is what makes it
do so here.) -/
theorem depthOneGroup_subgroupOf :
    (depthOneGroup C_X C_Z).subgroupOf (codePreservingGroup C_X C_Z)
      = ⨆ σ : {σ : Equiv.Perm ι // Function.Involutive σ},
          (fixedMatchingSlice C_X C_Z σ.1 σ.2).subgroupOf (codePreservingGroup C_X C_Z) := by
  refine Subgroup.map_subtype_inj.mp ?_
  rw [Subgroup.subgroupOf_map_subtype, Subgroup.map_iSup,
    inf_eq_left.mpr depthOneGroup_le_codePreservingGroup]
  simp only [depthOneGroup]
  refine iSup_congr fun σ => ?_
  rw [Subgroup.subgroupOf_map_subtype,
    inf_eq_left.mpr (fixedMatchingSlice_le_codePreservingGroup C_X C_Z σ.1 σ.2)]

/-- **Corollary (Depth-one logical generation)**, *Beyond transversality*, App. D, Eq. `d1-log`. For
an isotropic label space
`𝒞` — so that the logical action `λ = logicalActionHom : N_full ↠ Sp(2k)` is the paper's map — the
logical image of the depth-one group is generated by the logical images of the three depth-one
families, over all matchings:
`λ(N_dep) = ⟨ ⋃_M λ(S^Z_M ∪ S^X_M ∪ L_M) ⟩`, rendered in the subgroup lattice as
`⨆_M (λ(S^Z_M) ⊔ λ(S^X_M) ⊔ λ(L_M))`.

Proof (the paper's): `λ` is a homomorphism, so it distributes over the join over matchings
(`Subgroup.map_iSup`, via `depthOneGroup_subgroupOf`); one slice at a time, Theorem D.1
(`fixedMatchingSlice_eq_sup_familyM`) gives `N_M = S^Z_M ⊔ S^X_M ⊔ L_M`, and `λ` maps a join of
subgroups to the join of images (`Subgroup.map_sup`). The isotropy hypothesis `_hiso` fixes the
paper's scope (it is what makes the codomain `Sp(2k)`); the equation holds for any label space, so
the proof does not consume it. -/
theorem logicalAction_depthOneGroup_eq
    (_hiso : IsIsotropic (cssLabelSpaceSum C_X C_Z)) :
    Subgroup.map logicalActionHom
        ((depthOneGroup C_X C_Z).subgroupOf (codePreservingGroup C_X C_Z))
      = ⨆ σ : {σ : Equiv.Perm ι // Function.Involutive σ},
          (Subgroup.map logicalActionHom
              ((shearZFamilyM C_X C_Z σ.1 σ.2).subgroupOf (codePreservingGroup C_X C_Z))
            ⊔ Subgroup.map logicalActionHom
              ((shearXFamilyM C_X C_Z σ.1 σ.2).subgroupOf (codePreservingGroup C_X C_Z))
            ⊔ Subgroup.map logicalActionHom
              ((leviFamilyM C_X C_Z σ.1 σ.2).subgroupOf (codePreservingGroup C_X C_Z))) := by
  rw [depthOneGroup_subgroupOf, Subgroup.map_iSup]
  refine iSup_congr fun σ => ?_
  rw [fixedMatchingSlice_eq_sup_familyM σ.2,
    Subgroup.subgroupOf_sup
      (sup_le (shearZFamilyM_le_codePreservingGroup C_X C_Z σ.1 σ.2)
        (shearXFamilyM_le_codePreservingGroup C_X C_Z σ.1 σ.2))
      ((leviFamilyM_le_fixedMatchingSlice C_X C_Z σ.1 σ.2).trans
        (fixedMatchingSlice_le_codePreservingGroup C_X C_Z σ.1 σ.2)),
    Subgroup.subgroupOf_sup
      (shearZFamilyM_le_codePreservingGroup C_X C_Z σ.1 σ.2)
      (shearXFamilyM_le_codePreservingGroup C_X C_Z σ.1 σ.2),
    Subgroup.map_sup, Subgroup.map_sup]

end CliffordCSS
