import CliffordCSS.DepthOne.Supply
import CliffordCSS.DepthOne.ShearLevi

/-!
# The three depth-one generating families `S^Z_M`, `S^X_M`, `L_M`
(Beyond transversality, App. D.1 — Eq. (D2) and the easy half of Theorem D.1)

Pure mathematics : the three generating families of the
fixed-matching generation theorem (Theorem D.1, `thm-depthone`) of *Beyond transversality*
(arXiv:2608.05688), as subgroups of the binary symplectic group `Sp(2n, 𝔽₂)`, and the **easy
inclusion** `⟨S^Z_M, S^X_M, L_M⟩ ≤ N_M` — one half of Eq. (D3). Everything is `𝔽₂` symplectic
linear algebra naming the raw carrier `Matrix`.

## The paper's families (§D.1, Eq. (D2), Conventions c5/c6/c8)

The paper first fixes the three *dense* families of Appendix B — the valid `Z`-diagonal circuits,
the valid `X`-diagonal circuits, and the Levi (linear) part — and then takes their
`M`-block-diagonal slices:
```
  S^Z_M = S^Z ∩ 𝒟_M, S^X_M = S^X ∩ 𝒟_M, L_M = L ∩ 𝒟_M.
```

* **`S^Z` (`shearZFamily`)** — the valid `Z`-diagonal circuits `U_Z(S)` with `S` symmetric and
  `C_X S ⊆ C_Z`, i.e. `{U_Z(S) : S ∈ admissibleZParams C_X C_Z}`. Since `U_Z(S) U_Z(S') = U_Z(S+S')`
  and the admissible parameters form a subspace, it is a subgroup; each `U_Z(S)` preserves `𝒞`
  (`shearZFamily_le_codePreservingGroup`), so `S^Z ≤ N`.
* **`S^X` (`shearXFamily`)** — dually the valid `X`-diagonal circuits `L_X(T)` with `T` symmetric
  and `C_Z T ⊆ C_X`, i.e. `{L_X(T) : T ∈ admissibleXParams C_X C_Z}`; `S^X ≤ N`.
* **`L` (`leviFamily`)** — Convention c8's `L := {Levi(K) : K ∈ GL(n)} ∩ N`, the code-preserving
  Levi gates. We take the whole Levi subgroup `leviGroup = {Levi(K) : K ∈ GL(n)}` (a genuine
  subgroup: `Levi(K) Levi(K') = Levi(K K')`) and intersect with the code-preserving group,
  `leviFamily = leviGroup ⊓ N`, so `L ≤ N` is immediate.

The **`M`-parts** are `𝒟_M`-intersections, `shearZFamilyM = shearZFamily ⊓ 𝒟_M`, etc. All three have
the same shape — an intersection of subgroups of `Sp(2n)` — so each is a subgroup, and since each
dense family lies in `N`, each `M`-part lies in `𝒟_M ∩ N = N_M` (`fixedMatchingSlice`). The subgroup
generated by the three families is their join `S^Z_M ⊔ S^X_M ⊔ L_M`; the easy inclusion
`sup_familyM_le_fixedMatchingSlice` records `S^Z_M ⊔ S^X_M ⊔ L_M ≤ N_M`, the `≤` half of Eq. (D3).
The reverse (harder) inclusion `N_M ≤ ⟨…⟩` is Theorem D.1's content, delivered by the reduction
lemmas D.2–D.7 in later PRs.

No orthogonality `C_X ⊥ C_Z` is used — "a statement about split subspaces and nothing more".

## What is defined and proved

* `leviGroup` — the full Levi subgroup `{Levi(K) : K ∈ GL(n)}` of `Sp(2n, 𝔽₂)`.
* `shearZFamily` / `shearXFamily` — the dense `Z`- / `X`-diagonal families `S^Z`, `S^X`, as
  subgroups.
* `leviFamily` — the code-preserving Levi family `L = leviGroup ⊓ N` (Convention c8).
* `shearZFamily_le_codePreservingGroup` / `shearXFamily_le_codePreservingGroup` /
  `leviFamily_le_codePreservingGroup` — each dense family preserves the code, `· ≤ N`.
* `leviGate_mem_codePreservingGroup_iff` — Convention c8's criterion `Levi(K) ∈ N ↔ C_X K ⊆ C_X ∧
  C_Z K⁻ᵀ ⊆ C_Z`, and `mem_leviFamily_iff` — the fully unfolded Levi-family membership
  `G ∈ L ↔ ∃ K, G = Levi(K) ∧ C_X K ⊆ C_X ∧ C_Z K⁻ᵀ ⊆ C_Z`.
* `shearZFamilyM` / `shearXFamilyM` / `leviFamilyM` — the `M`-block-diagonal parts `S^Z_M`, `S^X_M`,
  `L_M` (Eq. (D2)), with the intersection-form membership lemmas `mem_*FamilyM`.
* `shearZFamilyM_le_fixedMatchingSlice` / `…X…` / `…levi…` — each `M`-family lies in `N_M`.
* `sup_familyM_le_fixedMatchingSlice` — the easy inclusion `S^Z_M ⊔ S^X_M ⊔ L_M ≤ N_M` of Eq. (D3).
-/

open Matrix

namespace CliffordCSS

variable {ι : Type*} [Fintype ι] [DecidableEq ι]

/-! ### The Levi subgroup `L = {Levi(K) : K ∈ GL(n)}` -/

/-- The **Levi subgroup** `{Levi(K) : K ∈ GL(n)}` of `Sp(2n, 𝔽₂)` (Convention c8, before the code
constraint): the symplectic matrices of the form `Levi(K) = [[K, 0], [0, K⁻ᵀ]]` for some invertible
`K`. It is a genuine subgroup — `Levi(K) Levi(K') = Levi(K K')` (`leviGate_mul`), `Levi(1) = 1`
(`leviGate_one`), and the inverse is again a Levi gate `Levi(K)⁻¹ = Levi(K⁻¹)` (via the `𝔽₂` inverse
formula `coe_inv_eq_fromBlocks`). The paper's Levi family `L` is this group intersected with the
code-preserving group `N` (`leviFamily`). -/
def leviGroup : Subgroup ↥(binarySymplecticGroup ι) where
  carrier := {G |
    ∃ K : (Matrix ι ι (ZMod 2))ˣ,
      (G : Matrix (ι ⊕ ι) (ι ⊕ ι) (ZMod 2)) = leviGate K}
  one_mem' := ⟨1, by rw [Submonoid.coe_one, leviGate_one]⟩
  mul_mem' := by
    rintro G H ⟨K, hK⟩ ⟨K', hK'⟩
    exact ⟨K * K', by rw [Submonoid.coe_mul, hK, hK', leviGate_mul]⟩
  inv_mem' := by
    rintro G ⟨K, hK⟩
    refine ⟨K⁻¹, ?_⟩
    have hK' : (G : Matrix (ι ⊕ ι) (ι ⊕ ι) (ZMod 2))
        = Matrix.fromBlocks (K : Matrix ι ι (ZMod 2)) 0 0 ((↑K⁻¹ : Matrix ι ι (ZMod 2))ᵀ) := by
      rw [hK, leviGate]
    rw [coe_inv_eq_fromBlocks hK', leviGate]
    simp only [Matrix.transpose_transpose, Matrix.transpose_zero, inv_inv]


/-! ### The dense `Z`- and `X`-diagonal families `S^Z`, `S^X` -/

/-- The **`Z`-diagonal family** `S^Z` of *Beyond transversality* (§D.1, Convention c6) as a subgroup
of `Sp(2n, 𝔽₂)`: the valid `Z`-diagonal circuits `U_Z(S)` whose parameter `S` is symmetric and
satisfies `C_X S ⊆ C_Z`, i.e. `S ∈ admissibleZParams C_X C_Z`. It is a subgroup because the
admissible parameters form a subspace and `U_Z(S) U_Z(S') = U_Z(S + S')` (`shearZ_mul`), with each
`U_Z(S)` its own inverse over `𝔽₂` (`shearZ_mul_self`). -/
def shearZFamily (C_X C_Z : Submodule (ZMod 2) (ι → ZMod 2)) :
    Subgroup ↥(binarySymplecticGroup ι) where
  carrier := {G |
    ∃ S ∈ admissibleZParams C_X C_Z, (G : Matrix (ι ⊕ ι) (ι ⊕ ι) (ZMod 2)) = shearZ S}
  one_mem' := ⟨0, Submodule.zero_mem _, by rw [Submonoid.coe_one, shearZ_zero]⟩
  mul_mem' := by
    rintro G H ⟨S, hS, hGS⟩ ⟨S', hS', hHS'⟩
    exact ⟨S + S', Submodule.add_mem _ hS hS', by rw [Submonoid.coe_mul, hGS, hHS', shearZ_mul]⟩
  inv_mem' := by
    rintro G ⟨S, hS, hGS⟩
    refine ⟨S, hS, ?_⟩
    have hGG : G * G = 1 := by
      apply Subtype.ext
      rw [Submonoid.coe_mul, Submonoid.coe_one, hGS, shearZ_mul_self]
    rw [inv_eq_of_mul_eq_one_right hGG]; exact hGS


/-- The **`X`-diagonal family** `S^X` of *Beyond transversality* (the `X ↔ Z` dual of `S^Z`) as a
subgroup of `Sp(2n, 𝔽₂)`: the valid `X`-diagonal circuits `L_X(T)` whose parameter `T` is symmetric
and satisfies `C_Z T ⊆ C_X`, i.e. `T ∈ admissibleXParams C_X C_Z = admissibleParams C_Z C_X`. -/
def shearXFamily (C_X C_Z : Submodule (ZMod 2) (ι → ZMod 2)) :
    Subgroup ↥(binarySymplecticGroup ι) where
  carrier := {G |
    ∃ T ∈ admissibleXParams C_X C_Z, (G : Matrix (ι ⊕ ι) (ι ⊕ ι) (ZMod 2)) = shearX T}
  one_mem' := ⟨0, Submodule.zero_mem _, by rw [Submonoid.coe_one, shearX_zero]⟩
  mul_mem' := by
    rintro G H ⟨T, hT, hGT⟩ ⟨T', hT', hHT'⟩
    exact ⟨T + T', Submodule.add_mem _ hT hT', by rw [Submonoid.coe_mul, hGT, hHT', shearX_mul]⟩
  inv_mem' := by
    rintro G ⟨T, hT, hGT⟩
    refine ⟨T, hT, ?_⟩
    have hGG : G * G = 1 := by
      apply Subtype.ext
      rw [Submonoid.coe_mul, Submonoid.coe_one, hGT, shearX_mul_self]
    rw [inv_eq_of_mul_eq_one_right hGG]; exact hGT


/-- The **Levi family** `L` of *Beyond transversality* (Convention c8): the code-preserving Levi
gates, `L := {Levi(K) : K ∈ GL(n)} ∩ N = leviGroup ⊓ N`. -/
def leviFamily (C_X C_Z : Submodule (ZMod 2) (ι → ZMod 2)) :
    Subgroup ↥(binarySymplecticGroup ι) :=
  leviGroup ⊓ codePreservingGroup C_X C_Z

/-- Membership in the Levi family: `G ∈ L` iff `G = Levi(K)` for some invertible `K` and `G`
preserves the code. -/
theorem mem_leviFamily {C_X C_Z : Submodule (ZMod 2) (ι → ZMod 2)}
    {G : ↥(binarySymplecticGroup ι)} :
    G ∈ leviFamily C_X C_Z ↔ G ∈ leviGroup ∧ G ∈ codePreservingGroup C_X C_Z :=
  Subgroup.mem_inf

/-! ### Each dense family preserves the code, `· ≤ N` -/

/-- **`S^Z ≤ N`.** Every valid `Z`-diagonal circuit `U_Z(S) = [[1, S], [0, 1]]` preserves the CSS
code: via the validity characterization `mem_codePreservingGroup_fromBlocks_iff`, its four block
inclusions read `C_X · 1 ⊆ C_X`, `C_X S ⊆ C_Z` (the admissibility of `S`), `C_Z · 0 ⊆ C_X`,
`C_Z · 1 ⊆ C_Z`. -/
theorem shearZFamily_le_codePreservingGroup (C_X C_Z : Submodule (ZMod 2) (ι → ZMod 2)) :
    shearZFamily C_X C_Z ≤ codePreservingGroup C_X C_Z := by
  rintro G ⟨S, hS, hGS⟩
  rw [mem_admissibleParams] at hS
  have hG : (G : Matrix (ι ⊕ ι) (ι ⊕ ι) (ZMod 2)) = Matrix.fromBlocks 1 S 0 1 := by
    rw [hGS, shearZ]
  rw [mem_codePreservingGroup_fromBlocks_iff hG]
  refine ⟨fun x hx => ?_, fun x hx => hS.2 x hx, fun z _ => ?_, fun z hz => ?_⟩
  · rw [Matrix.vecMul_one]; exact hx
  · rw [Matrix.vecMul_zero]; exact C_X.zero_mem
  · rw [Matrix.vecMul_one]; exact hz

/-- **`S^X ≤ N`.** Dual to `shearZFamily_le_codePreservingGroup`: for `L_X(T) = [[1, 0], [T, 1]]`
the four block inclusions read `C_X · 1 ⊆ C_X`, `C_X · 0 ⊆ C_Z`, `C_Z T ⊆ C_X` (the admissibility
of `T`), `C_Z · 1 ⊆ C_Z`. -/
theorem shearXFamily_le_codePreservingGroup (C_X C_Z : Submodule (ZMod 2) (ι → ZMod 2)) :
    shearXFamily C_X C_Z ≤ codePreservingGroup C_X C_Z := by
  rintro G ⟨T, hT, hGT⟩
  rw [mem_admissibleParams] at hT
  have hG : (G : Matrix (ι ⊕ ι) (ι ⊕ ι) (ZMod 2)) = Matrix.fromBlocks 1 0 T 1 := by
    rw [hGT, shearX]
  rw [mem_codePreservingGroup_fromBlocks_iff hG]
  refine ⟨fun x hx => ?_, fun x _ => ?_, fun z hz => hT.2 z hz, fun z hz => ?_⟩
  · rw [Matrix.vecMul_one]; exact hx
  · rw [Matrix.vecMul_zero]; exact C_Z.zero_mem
  · rw [Matrix.vecMul_one]; exact hz

/-- **`L ≤ N`.** The Levi family is code-preserving by construction (`leviFamily = leviGroup ⊓ N`).
-/
theorem leviFamily_le_codePreservingGroup (C_X C_Z : Submodule (ZMod 2) (ι → ZMod 2)) :
    leviFamily C_X C_Z ≤ codePreservingGroup C_X C_Z :=
  inf_le_right

/-! ### Convention c8's code-preservation criterion for the Levi gate -/


/-! ### The `M`-block-diagonal families `S^Z_M`, `S^X_M`, `L_M` (Eq. (D2)) -/

variable (C_X C_Z : Submodule (ZMod 2) (ι → ZMod 2)) (σ : Equiv.Perm ι)
  (hσ : Function.Involutive σ)

/-- The **`M`-block-diagonal `Z`-diagonal family** `S^Z_M = S^Z ∩ 𝒟_M` (§D.1, Eq. (D2)): the
`M`-block-diagonal part of the dense family `S^Z`, for a matching `M` given by an involution `σ`. -/
def shearZFamilyM : Subgroup ↥(binarySymplecticGroup ι) :=
  shearZFamily C_X C_Z ⊓ blockDiagonalSymplecticGroup σ hσ

/-- The **`M`-block-diagonal `X`-diagonal family** `S^X_M = S^X ∩ 𝒟_M` (§D.1, Eq. (D2)). -/
def shearXFamilyM : Subgroup ↥(binarySymplecticGroup ι) :=
  shearXFamily C_X C_Z ⊓ blockDiagonalSymplecticGroup σ hσ

/-- The **`M`-block-diagonal Levi family** `L_M = L ∩ 𝒟_M` (§D.1, Eq. (D2)): the Levi gates that
are code-preserving and `M`-block-diagonal (Convention c6: "the Levi gates whose matrix `K` is in
addition `M`-block-diagonal"). -/
def leviFamilyM : Subgroup ↥(binarySymplecticGroup ι) :=
  leviFamily C_X C_Z ⊓ blockDiagonalSymplecticGroup σ hσ

/-- Membership in `S^Z_M`: `G ∈ S^Z_M` iff `G ∈ S^Z` and `G` is `M`-block-diagonal. -/
theorem mem_shearZFamilyM {G : ↥(binarySymplecticGroup ι)} :
    G ∈ shearZFamilyM C_X C_Z σ hσ ↔
      G ∈ shearZFamily C_X C_Z ∧ IsSpBlockDiagonal σ (G : Matrix (ι ⊕ ι) (ι ⊕ ι) (ZMod 2)) := by
  rw [shearZFamilyM, Subgroup.mem_inf, mem_blockDiagonalSymplecticGroup_iff]


/-- Membership in `S^X_M`: `G ∈ S^X_M` iff `G ∈ S^X` and `G` is `M`-block-diagonal. -/
theorem mem_shearXFamilyM {G : ↥(binarySymplecticGroup ι)} :
    G ∈ shearXFamilyM C_X C_Z σ hσ ↔
      G ∈ shearXFamily C_X C_Z ∧ IsSpBlockDiagonal σ (G : Matrix (ι ⊕ ι) (ι ⊕ ι) (ZMod 2)) := by
  rw [shearXFamilyM, Subgroup.mem_inf, mem_blockDiagonalSymplecticGroup_iff]


/-- Membership in `L_M`: `G ∈ L_M` iff `G ∈ L` (code-preserving Levi) and `G` is `M`-block-diagonal.
-/
theorem mem_leviFamilyM {G : ↥(binarySymplecticGroup ι)} :
    G ∈ leviFamilyM C_X C_Z σ hσ ↔
      G ∈ leviFamily C_X C_Z ∧ IsSpBlockDiagonal σ (G : Matrix (ι ⊕ ι) (ι ⊕ ι) (ZMod 2)) := by
  rw [leviFamilyM, Subgroup.mem_inf, mem_blockDiagonalSymplecticGroup_iff]


/-! ### Each `M`-block-diagonal family preserves the code, `·_M ≤ N` -/

/-- `S^Z_M ≤ N`: the `M`-block-diagonal `Z`-diagonal family is code-preserving, since
`S^Z_M = S^Z ⊓ 𝒟_M ≤ S^Z ≤ N` (`shearZFamily_le_codePreservingGroup`). Companion to
`shearZFamilyM_le_fixedMatchingSlice`, kept with the family-ordering lemmas and reused by the
terminal-factorization / reduction PRs (where a diagonal factor's code-preservation is needed
directly, not only its slice membership). -/
theorem shearZFamilyM_le_codePreservingGroup :
    shearZFamilyM C_X C_Z σ hσ ≤ codePreservingGroup C_X C_Z := by
  rw [shearZFamilyM]
  exact le_trans inf_le_left (shearZFamily_le_codePreservingGroup C_X C_Z)

/-- `S^X_M ≤ N` (dual to `shearZFamilyM_le_codePreservingGroup`): `S^X_M = S^X ⊓ 𝒟_M ≤ S^X ≤ N`. -/
theorem shearXFamilyM_le_codePreservingGroup :
    shearXFamilyM C_X C_Z σ hσ ≤ codePreservingGroup C_X C_Z := by
  rw [shearXFamilyM]
  exact le_trans inf_le_left (shearXFamily_le_codePreservingGroup C_X C_Z)

/-! ### The easy inclusion `⟨S^Z_M, S^X_M, L_M⟩ ≤ N_M` (Eq. (D3), `≤` half) -/

/-- `S^Z_M ≤ N_M`: the `M`-block-diagonal `Z`-diagonal family lies in the two-fold transversal
slice, since `S^Z ≤ N` (`shearZFamily_le_codePreservingGroup`) and `N_M = N ⊓ 𝒟_M`. -/
theorem shearZFamilyM_le_fixedMatchingSlice :
    shearZFamilyM C_X C_Z σ hσ ≤ fixedMatchingSlice C_X C_Z σ hσ := by
  rw [shearZFamilyM, fixedMatchingSlice]
  exact inf_le_inf (shearZFamily_le_codePreservingGroup C_X C_Z) le_rfl

/-- `S^X_M ≤ N_M` (dual to `shearZFamilyM_le_fixedMatchingSlice`). -/
theorem shearXFamilyM_le_fixedMatchingSlice :
    shearXFamilyM C_X C_Z σ hσ ≤ fixedMatchingSlice C_X C_Z σ hσ := by
  rw [shearXFamilyM, fixedMatchingSlice]
  exact inf_le_inf (shearXFamily_le_codePreservingGroup C_X C_Z) le_rfl

/-- `L_M ≤ N_M`: the `M`-block-diagonal Levi family lies in the two-fold transversal slice, since
`L ≤ N` (`leviFamily_le_codePreservingGroup`) and `N_M = N ⊓ 𝒟_M`. -/
theorem leviFamilyM_le_fixedMatchingSlice :
    leviFamilyM C_X C_Z σ hσ ≤ fixedMatchingSlice C_X C_Z σ hσ := by
  rw [leviFamilyM, fixedMatchingSlice]
  exact inf_le_inf (leviFamily_le_codePreservingGroup C_X C_Z) le_rfl

/-- **The easy inclusion of Theorem D.1 (Eq. (D3), `≤` half).** The subgroup generated by the three
`M`-block-diagonal families — their join `S^Z_M ⊔ S^X_M ⊔ L_M` — is contained in the two-fold
transversal slice `N_M`. Each family already lies in `N_M`
(`shearZFamilyM_le_fixedMatchingSlice`, `shearXFamilyM_le_fixedMatchingSlice`,
`leviFamilyM_le_fixedMatchingSlice`), so their join is too. The reverse inclusion `N_M ≤ ⟨…⟩` — the
substance of Theorem D.1 — is the subject of the reduction lemmas D.2–D.7. -/
theorem sup_familyM_le_fixedMatchingSlice :
    shearZFamilyM C_X C_Z σ hσ ⊔ shearXFamilyM C_X C_Z σ hσ ⊔ leviFamilyM C_X C_Z σ hσ
      ≤ fixedMatchingSlice C_X C_Z σ hσ :=
  sup_le
    (sup_le (shearZFamilyM_le_fixedMatchingSlice C_X C_Z σ hσ)
      (shearXFamilyM_le_fixedMatchingSlice C_X C_Z σ hσ))
    (leviFamilyM_le_fixedMatchingSlice C_X C_Z σ hσ)

end CliffordCSS
