import CliffordCSS.Symplectic.CliffordAction
import CliffordCSS.Encoding.CnotNetwork
import CliffordCSS.ToMathlib.Data.Matrix.Basis

/-!
# The symplectic images of the elementary Clifford gates (Beyond transversality, App. D)

Pure mathematics : the `2n × 2n` matrices over `𝔽₂ = ZMod 2` through
which the two remaining elementary Clifford gates — the single-wire **Hadamard** `H_j` and the
two-wire **CNOT** `CNOT_{c→t}` — act on Pauli labels, in the row-vector convention of
`CliffordCSS.cliffordSymplectic`. The third gate, the phase gate, is already identified with a
`Z`-shear in `CliffordSymplecticAction.lean` (`cliffordSymplectic_phase = shearZ (single j j 1)`);
this file supplies the two the header of that file deliberately deferred.

These three gate images are the **generators** whose closure is the object of work item **W1** of
the certificate-route plan for Theorem D.1 (`dec-conditional-d1-certificate-route`): *the binary
symplectic group `Sp(2n, 𝔽₂)` is generated by the symplectic images of the elementary Clifford
gates* (equivalently `cliffordSymplectic` is surjective onto `binarySymplecticGroup (Fin n)`). This
file lands the generators themselves; the closure/surjectivity theorem comes later.

## The gate images, in the `(x | z)` label convention

A label is a row vector `(x | z) ∈ 𝔽₂^{2n}` acted on from the right, `label ↦ label ᵥ*
cliffordSymplectic U` (Convention c2 of *Beyond transversality*; `checkVec_act`). Reading off the
single-qubit check-bit tableaux of the two gates:

* **Hadamard on wire `j`** exchanges the `X`- and `Z`-bits of wire `j` and fixes every other bit
  (`pauliBit_hadamardPauli`: `(x_j, z_j) ↦ (z_j, x_j)`). Its matrix is the coordinate swap
  `inl j ↔ inr j`, the block matrix `hadamardSymplectic j = [[I + E_{jj}, E_{jj}], [E_{jj}, I +
  E_{jj}]]` (over `𝔽₂`, `I + E_{jj}` is the diagonal that is `0` at `j` and `1` elsewhere).
* **CNOT `c → t`** adds the control's `X`-bit into the target's (`x_t ↦ x_t + x_c`) and the target's
  `Z`-bit into the control's (`z_c ↦ z_c + z_t`), fixing every other bit
  (`pauliBit_cnotCtrlPauli` / `pauliBit_cnotTgtPauli`). Its matrix is **block-diagonal**,
  `cnotSymplectic c t = [[I + E_{ct}, 0], [0, I + E_{tc}]]` — the Levi (block-diagonal) gate of the
  transvection `I + E_{ct}` (which over `𝔽₂` is its own inverse, and `(I + E_{ct})⁻ᵀ = I + E_{tc}`).

## What is proved

Each gate is handled by the same two-step used for the phase gate: compute the linear label action
`cliffordLabelMap [gate]` (`cliffordLabelMap_had` / `cliffordLabelMap_cnot`), then transport it to
the matrix via injectivity of the right action
(`cliffordSymplectic_had` / `cliffordSymplectic_cnot`).

* `pauliBit_hadamardPauli` — the `ZMod 2` check-bit form of the Hadamard tableau, the swap
  `(x, z) ↦ (z, x)`.
* `hadamardSymplectic` / `vecMul_hadamardSymplectic` — the Hadamard matrix and its right action
  (the coordinate swap `inl j ↔ inr j`).
* `cliffordLabelMap_had` / `cliffordSymplectic_had` — the Hadamard gate acts by
  `hadamardSymplectic`.
* `hadamardSymplectic_mem_binarySymplecticGroup` — it lies in `Sp(2n, 𝔽₂)`.
* `cnotSymplectic` / `vecMul_cnotSymplectic` — the CNOT matrix and its right action (`x_t += x_c`,
  `z_c += z_t`).
* `cliffordLabelMap_cnot` / `cliffordSymplectic_cnot` — the CNOT gate acts by `cnotSymplectic`.
* `cnotSymplectic_mem_binarySymplecticGroup` — it lies in `Sp(2n, 𝔽₂)`.

## Placement

The gate images quantify over the raw carrier `Matrix … (ZMod 2)` and the `cliffordSymplectic`
carrier accessor; this is pure `𝔽₂` linear algebra, so — like
`CliffordSymplecticAction.lean` and `BinarySymplecticGroup.lean`.
-/

open Matrix

namespace CliffordCSS

variable {n : ℕ}

/-! ### The Hadamard gate is the coordinate swap `X_j ↔ Z_j` -/

/-- The `ZMod 2` check-bit form of the **Hadamard tableau**: `H` exchanges the `X`- and `Z`-bits of
its wire, `pauliBit (hadamardPauli a) = (z_a, x_a)`. A `4`-case check; the `ℕ`-valued halves are
`pauliXBit_hadamardPauli` / `pauliZBit_hadamardPauli`. -/
theorem pauliBit_hadamardPauli (a : Fin 4) :
    pauliBit (hadamardPauli a) = ((pauliBit a).2, (pauliBit a).1) := by
  fin_cases a <;> decide

/-- **The single-wire Hadamard symplectic matrix** `H_j`: the `2n × 2n` matrix over `𝔽₂` that swaps
the `X`- and `Z`-labels of wire `j` and fixes every other label. In the polarized block form it is
`[[I + E_{jj}, E_{jj}], [E_{jj}, I + E_{jj}]]` with `E_{jj} = single j j 1` — over `𝔽₂`,
`I + E_{jj}` is the identity with its `(j, j)` entry flipped to `0`. It is the symplectic image of
the Clifford
gate `had j` (`cliffordSymplectic_had`). -/
def hadamardSymplectic (j : Fin n) : Matrix (Fin n ⊕ Fin n) (Fin n ⊕ Fin n) (ZMod 2) :=
  Matrix.fromBlocks (1 + Matrix.single j j 1) (Matrix.single j j 1)
    (Matrix.single j j 1) (1 + Matrix.single j j 1)

/-- **The right action of the Hadamard matrix is the coordinate swap `inl j ↔ inr j`**: on a label
`(a | b)` it exchanges the `j`-th `X`-bit `a j` and `j`-th `Z`-bit `b j`, leaving all others fixed,
`(a | b) ᵥ* H_j = (a with a_j := b_j | b with b_j := a_j)`. -/
theorem vecMul_hadamardSymplectic (j : Fin n) (a b : Fin n → ZMod 2) :
    (Sum.elim a b) ᵥ* hadamardSymplectic j
      = Sum.elim (Function.update a j (b j)) (Function.update b j (a j)) := by
  rw [hadamardSymplectic, vecMul_fromBlocks_blocks, Matrix.vecMul_add, Matrix.vecMul_add,
    Matrix.vecMul_one, Matrix.vecMul_one, Matrix.vecMul_single, Matrix.vecMul_single, mul_one,
    mul_one]
  ext (k | k) <;> simp only [Sum.elim_inl, Sum.elim_inr, Pi.add_apply, Function.update_apply,
    Pi.zero_apply] <;> by_cases hk : k = j <;> simp [hk, CharTwo.add_self_eq_zero]

/-- **The label action of the Hadamard gate on wire `j` is the coordinate swap `H_j`**:
`cliffordLabelMap [had j] v = v ᵥ* hadamardSymplectic j`. The per-generator computation behind
`cliffordSymplectic_had`, the Hadamard analogue of `cliffordLabelMap_phase`. -/
theorem cliffordLabelMap_had (j : Fin n) (v : Fin n ⊕ Fin n → ZMod 2) :
    cliffordLabelMap [CliffordGate.had j] v = v ᵥ* hadamardSymplectic j := by
  rw [← Sum.elim_comp_inl_inr v, vecMul_hadamardSymplectic]
  refine cliffordLabelMap_eq_of_pauliBit fun k => ?_
  rcases eq_or_ne k j with rfl | hk
  · rw [CliffordCircuit.act, CliffordGate.act, Function.update_self, pauliBit_hadamardPauli]
    simp [vecPauli, pauliBit_bitToPauli, CliffordCircuit.act]
  · rw [CliffordCircuit.act, CliffordGate.act, Function.update_of_ne hk]
    simp [vecPauli, pauliBit_bitToPauli, Function.update_of_ne hk, CliffordCircuit.act]

/-- **The single-wire Hadamard gate is the coordinate swap `H_j`**:
`cliffordSymplectic [had j] = hadamardSymplectic j`. Together with the phase gate
(`cliffordSymplectic_phase`) and CNOT (`cliffordSymplectic_cnot`) this identifies the symplectic
image of every elementary Clifford generator. -/
theorem cliffordSymplectic_had (j : Fin n) :
    cliffordSymplectic [CliffordGate.had j] = hadamardSymplectic j :=
  cliffordSymplectic_eq_of_labelMap (cliffordLabelMap_had j)


/-! ### The CNOT gate is the block-diagonal transvection pair -/

/-- **The CNOT symplectic matrix** `CNOT_{c→t}`: the `2n × 2n` matrix over `𝔽₂` that adds the
control's `X`-bit into the target's (`x_t ↦ x_t + x_c`) and the target's `Z`-bit into the control's
(`z_c ↦ z_c + z_t`), fixing every other bit. It is **block-diagonal**,
`[[I + E_{ct}, 0], [0, I + E_{tc}]]` with `E_{ct} = single c t 1` — the Levi gate of the elementary
transvection `I + E_{ct}`. It is the symplectic image of the Clifford gate `cnot c t`
(`cliffordSymplectic_cnot`). -/
def cnotSymplectic (c t : Fin n) : Matrix (Fin n ⊕ Fin n) (Fin n ⊕ Fin n) (ZMod 2) :=
  Matrix.fromBlocks (1 + Matrix.single c t 1) 0 0 (1 + Matrix.single t c 1)

/-- **The right action of the CNOT matrix** (control `c`, target `t`, `c ≠ t`): on a label `(a | b)`
it adds `a c` into `a t` and `b t` into `b c`, `(a | b) ᵥ* CNOT_{c→t} = (a with a_t := a_t + a_c |
b with b_c := b_c + b_t)`. -/
theorem vecMul_cnotSymplectic (c t : Fin n) (h : c ≠ t) (a b : Fin n → ZMod 2) :
    (Sum.elim a b) ᵥ* cnotSymplectic c t
      = Sum.elim (Function.update a t (a t + a c)) (Function.update b c (b c + b t)) := by
  rw [cnotSymplectic, vecMul_fromBlocks_blocks, Matrix.vecMul_zero, Matrix.vecMul_zero,
    add_zero, zero_add, Matrix.vecMul_add, Matrix.vecMul_add, Matrix.vecMul_one, Matrix.vecMul_one,
    Matrix.vecMul_single, Matrix.vecMul_single, mul_one, mul_one]
  ext (k | k) <;> simp only [Sum.elim_inl, Sum.elim_inr, Pi.add_apply, Function.update_apply,
    Pi.zero_apply] <;> by_cases hk : k = t <;> by_cases hk2 : k = c <;> simp_all [add_comm]

/-- **The label action of the CNOT gate is the transvection pair `CNOT_{c→t}`**:
`cliffordLabelMap [cnot c t h] v = v ᵥ* cnotSymplectic c t`. The per-generator computation behind
`cliffordSymplectic_cnot`; the three cases are the control wire `c`, the target wire `t`, and the
untouched wires. -/
theorem cliffordLabelMap_cnot (c t : Fin n) (h : c ≠ t) (v : Fin n ⊕ Fin n → ZMod 2) :
    cliffordLabelMap [CliffordGate.cnot c t h] v = v ᵥ* cnotSymplectic c t := by
  rw [← Sum.elim_comp_inl_inr v, vecMul_cnotSymplectic _ _ h]
  refine cliffordLabelMap_eq_of_pauliBit fun k => ?_
  rcases eq_or_ne k c with rfl | hkc
  · rw [CliffordCircuit.act, CliffordGate.act, cnotPauliString_ctrl, pauliBit_cnotCtrlPauli]
    simp [vecPauli, pauliBit_bitToPauli, Function.comp, Function.update_of_ne h,
      CliffordCircuit.act]
  · rcases eq_or_ne k t with rfl | hkt
    · rw [CliffordCircuit.act, CliffordGate.act, cnotPauliString_tgt _ h, pauliBit_cnotTgtPauli]
      simp [vecPauli, pauliBit_bitToPauli, Function.comp, Function.update_of_ne (Ne.symm h),
        add_comm, CliffordCircuit.act]
    · rw [CliffordCircuit.act, CliffordGate.act, cnotPauliString_of_ne _ c t hkc hkt]
      simp [vecPauli, pauliBit_bitToPauli, Function.comp, Function.update_of_ne hkt,
        Function.update_of_ne hkc, CliffordCircuit.act]

/-- **The CNOT gate is the block-diagonal transvection pair `CNOT_{c→t}`**:
`cliffordSymplectic [cnot c t h] = cnotSymplectic c t`. -/
theorem cliffordSymplectic_cnot (c t : Fin n) (h : c ≠ t) :
    cliffordSymplectic [CliffordGate.cnot c t h] = cnotSymplectic c t :=
  cliffordSymplectic_eq_of_labelMap (cliffordLabelMap_cnot c t h)


end CliffordCSS
