import CliffordCSS.Symplectic.Generation
import CliffordCSS.Symplectic.Group
import CliffordCSS.DepthOne.ShearLevi
import CliffordCSS.ZMod2
import Mathlib.LinearAlgebra.Matrix.Transvection

/-!
# The Levi subgroup is generated by the CNOT gates (Beyond transversality, App. D)

Pure mathematics : every **Levi gate**
`leviGate K = [[K, 0], [0, K⁻ᵀ]]` (`K ∈ GL(n, 𝔽₂)`, *Beyond transversality* Convention c8) is the
symplectic image of a **CNOT circuit** —
`∃ U : CliffordCircuit n, cliffordSymplectic U = leviGate K`
(`exists_cliffordSymplectic_eq_leviGate`). Equivalently the block-diagonal (Levi) part of
`Sp(2n, 𝔽₂)`, which is isomorphic to `GL(n, 𝔽₂)` via `K ↦ leviGate K`, is generated by the two-wire
CNOT generators.

This is the **X-part engine** of the certificate-route generation result (work item **W1**,
`dec-conditional-d1-certificate-route`): once every `Sp(2n, 𝔽₂)` element's first row (the image of
`X₀`) has been brought into the top block, a Levi gate carries an arbitrary invertible top block to
the standard basis, and this lemma realizes that Levi gate by an explicit CNOT word. It is split off
from the fix-first-pair reduction as its own reusable piece (`dec-w1-split-levi-engine`).

## The generation, at a glance

Each elementary CNOT image is a single Levi transvection: `cnotSymplectic c t` has top-left block
`1 + E_{ct} = Matrix.transvection c t 1` (`CliffordCSS/Symplectic/Generation.lean`). Over `𝔽₂`,
Mathlib's Bruhat-style pivot decomposition `exists_list_transvec_mul_diagonal_mul_list_transvec`
writes any invertible `K` as `(∏ transvections) · diagonal D · (∏ transvections)`, and the diagonal
is forced to the identity: `det K` is a unit of `𝔽₂`, hence `1`, so `∏ Dᵢ = 1`, so every `Dᵢ = 1`.
Thus `K` is a product of transvections, each the top block of a CNOT image.

The one design subtlety is the **bottom** block. Building a CNOT word whose `cliffordSymplectic` has
a *prescribed* top block leaves the bottom block `Q` undetermined by the construction; rather than
track `Q = K⁻ᵀ` through the induction (which would thread inverse–transpose bookkeeping everywhere),
we leave `Q` existentially free in the core lemma
(`exists_cliffordSymplectic_fromBlocks_transvec_prod`) and **pin it afterwards by symplecticity**:
`cliffordSymplectic U` is always symplectic, and a block-diagonal `[[K, 0], [0, Q]] ∈ Sp(2n, 𝔽₂)`
forces `K Qᵀ = 1` (`fromBlocks_mem_binarySymplecticGroup_iff`), i.e. `Q = K⁻ᵀ`, whenever `K` is
invertible.

## Placement

The statement quantifies over the raw carrier `Matrix … (ZMod 2)`, the `cliffordSymplectic` carrier
accessor, and `leviGate`; this is pure `𝔽₂` linear algebra, so
— like `CliffordSymplecticGeneration.lean` and `BinarySymplecticGroup.lean`.lean` is a
docstring-only pointer.
-/

open Matrix

namespace CliffordCSS

variable {n : ℕ}

/-- **The core construction**: for any list `L` of transvection structures over `𝔽₂`, some CNOT
circuit `U` has `cliffordSymplectic U` block-diagonal with prescribed **top** block the product
`∏ Lᵢ` of the transvection matrices — the bottom block `Q` being left free (it is pinned to the
inverse-transpose afterwards by symplecticity). By induction along `L`: the empty list gives the
identity; a `c = 0` transvection is the identity and is skipped; a `c = 1` transvection `1 + E_{ij}`
is the top block of `cnotSymplectic i j`, prepended by functoriality of `cliffordSymplectic`. -/
private theorem exists_cliffordSymplectic_fromBlocks_transvec_prod
    (L : List (Matrix.TransvectionStruct (Fin n) (ZMod 2))) :
    ∃ (U : CliffordCircuit n) (Q : Matrix (Fin n) (Fin n) (ZMod 2)),
      cliffordSymplectic U
        = Matrix.fromBlocks (L.map Matrix.TransvectionStruct.toMatrix).prod 0 0 Q := by
  induction L with
  | nil => exact ⟨[], 1, by simp [Matrix.fromBlocks_one]⟩
  | cons t L ih =>
      obtain ⟨U, Q, hU⟩ := ih
      by_cases hc : t.c = 0
      · refine ⟨U, Q, ?_⟩
        have ht : t.toMatrix = 1 := by
          simp only [Matrix.TransvectionStruct.toMatrix, Matrix.transvection, hc,
            Matrix.single_zero, add_zero]
        rw [List.map_cons, List.prod_cons, ht, one_mul]
        exact hU
      · have hc1 : t.c = 1 := (zmod2_eq_zero_or_one t.c).resolve_left hc
        refine ⟨U ++ [CliffordGate.cnot t.i t.j t.hij],
          (1 + Matrix.single t.j t.i 1) * Q, ?_⟩
        have ht : t.toMatrix = 1 + Matrix.single t.i t.j 1 := by
          simp only [Matrix.TransvectionStruct.toMatrix, Matrix.transvection, hc1]
        rw [List.map_cons, List.prod_cons, ht, cliffordSymplectic_append,
          cliffordSymplectic_cnot t.i t.j t.hij, hU]
        simp [cnotSymplectic, Matrix.fromBlocks_multiply]

/-- **Every Levi gate is the symplectic image of a CNOT circuit.** For any invertible
`K ∈ GL(n, 𝔽₂)`, some Clifford circuit `U` (a word in the two-wire CNOT generators) satisfies
`cliffordSymplectic U = leviGate K`, where `leviGate K = [[K, 0], [0, K⁻ᵀ]]`. Equivalently the Levi
(block-diagonal) subgroup of `Sp(2n, 𝔽₂)` is generated by the CNOT gate images.

The `X`-part engine of the certificate-route generation result (work item **W1**): the CNOT images
realize the full `GL(n, 𝔽₂)`-worth of Levi transformations, which is what carries an arbitrary
invertible top block to the standard basis in the symplectic Gaussian elimination.

Proof: `K` decomposes over `𝔽₂` as a product of transvections (Mathlib's
`exists_list_transvec_mul_diagonal_mul_list_transvec`, with the diagonal factor forced to `1` since
`det K = 1`), each of which is the top block of a CNOT image; the core construction
`exists_cliffordSymplectic_fromBlocks_transvec_prod` assembles the word with that top block, and its
bottom block is pinned to `K⁻ᵀ` by symplecticity (`fromBlocks_mem_binarySymplecticGroup_iff`). -/
theorem exists_cliffordSymplectic_eq_leviGate
    (K : (Matrix (Fin n) (Fin n) (ZMod 2))ˣ) :
    ∃ U : CliffordCircuit n, cliffordSymplectic U = leviGate K := by
  obtain ⟨L, L', D, hK⟩ :=
    Matrix.Pivot.exists_list_transvec_mul_diagonal_mul_list_transvec
      (K : Matrix (Fin n) (Fin n) (ZMod 2))
  -- The diagonal factor of the Bruhat decomposition is the identity over `𝔽₂`.
  have hdet : (K : Matrix (Fin n) (Fin n) (ZMod 2)).det ≠ 0 :=
    ((Matrix.isUnit_iff_isUnit_det _).mp K.isUnit).ne_zero
  have hdetK1 : (K : Matrix (Fin n) (Fin n) (ZMod 2)).det = 1 :=
    (zmod2_eq_zero_or_one _).resolve_left hdet
  have hdetD : (Matrix.diagonal D).det = 1 := by
    have h := congrArg Matrix.det hK
    rw [Matrix.det_mul, Matrix.det_mul, Matrix.TransvectionStruct.det_toMatrix_prod,
      Matrix.TransvectionStruct.det_toMatrix_prod, one_mul, mul_one] at h
    exact h.symm.trans hdetK1
  rw [Matrix.det_diagonal] at hdetD
  have hD1 : ∀ i, D i = 1 := fun i => by
    rcases zmod2_eq_zero_or_one (D i) with h0 | h1
    · have hz : (∏ j, D j) = 0 := Finset.prod_eq_zero (Finset.mem_univ i) h0
      rw [hdetD] at hz
      exact absurd hz (by decide)
    · exact h1
  have hDone : Matrix.diagonal D = 1 := by
    rw [funext hD1]; exact Matrix.diagonal_one
  have hKP : (K : Matrix (Fin n) (Fin n) (ZMod 2))
      = (L.map Matrix.TransvectionStruct.toMatrix).prod
        * (L'.map Matrix.TransvectionStruct.toMatrix).prod := by
    rw [hK, hDone, mul_one]
  -- Assemble the CNOT word with top block `∏ transvections = K`.
  obtain ⟨U, Q, hU⟩ := exists_cliffordSymplectic_fromBlocks_transvec_prod (L ++ L')
  rw [List.map_append, List.prod_append, ← hKP] at hU
  refine ⟨U, ?_⟩
  -- Pin the bottom block by symplecticity: `K Qᵀ = 1`, so `Q = K⁻ᵀ`.
  have hmem : Matrix.fromBlocks (K : Matrix (Fin n) (Fin n) (ZMod 2)) 0 0 Q
      ∈ binarySymplecticGroup (Fin n) := by
    rw [← hU]; exact cliffordSymplectic_mem_binarySymplecticGroup U
  have hKQ : (K : Matrix (Fin n) (Fin n) (ZMod 2)) * Qᵀ = 1 := by
    have h := (fromBlocks_mem_binarySymplecticGroup_iff
      (K : Matrix (Fin n) (Fin n) (ZMod 2)) 0 0 Q).mp hmem
    simpa using h.2.2
  -- `hKQ` forces `Qᵀ = K⁻¹`, hence `Q = K⁻ᵀ`, the bottom block of `leviGate K`.
  rw [hU, ← Matrix.transpose_transpose Q, ← Units.inv_eq_of_mul_eq_one_right hKQ]
  rfl

end CliffordCSS
