import CliffordCSS.Symplectic.Generation
import CliffordCSS.Encoding.StandardForm
import CliffordCSS.DepthOne.ShearLevi

/-!
# The `Z`-shear subgroup is generated by the phase and controlled-`Z` gates

Pure mathematics : every **`Z`-shear** `U_Z(S) = [[I, S], [0, I]]`
with `S` symmetric (*Beyond transversality* Convention c7, `shearZ`) is the symplectic image of a
**phase / controlled-`Z` circuit** — `∃ U : CliffordCircuit n, cliffordSymplectic U = shearZ S`
(`exists_cliffordSymplectic_eq_shearZ`). Equivalently the `Z`-shear (diagonal) subgroup of
`Sp(2n, 𝔽₂)`, which is isomorphic to the additive group of symmetric matrices via `S ↦ U_Z(S)`
(`shearZ_mul`), is generated by the single-wire phase gates (the diagonal of `S`) and the two-wire
controlled-`Z` gates (the off-diagonal of `S`).

This is the **`Z`-part engine** of the certificate-route generation result (work item **W1**,
`dec-conditional-d1-certificate-route`), the diagonal companion to the Levi/`GL` engine
`exists_cliffordSymplectic_eq_leviGate` (`CliffordCSS/Symplectic/Levi.lean`, the `X`-part
engine). Together with the Levi engine and the elementary gate images it is what the symplectic
Gaussian elimination uses to clear the `Z`-coupling of a pivot wire.

## The generation, at a glance

The `Z`-shear is realized by the existing **phase / controlled-`Z` network**
`phaseCZNetwork (phaseWires S) (czPairs S)` (`CliffordCSS/Encoding/StandardForm.lean`,
N&C Problem 10.3): a phase gate `S` on each wire carrying a diagonal `1` of `S`, and a
controlled-`Z` on each strictly-ordered pair carrying an off-diagonal `1`. Its **check-row** action
is already computed (`checkRow_act_phaseCZNetwork`, `czCol_foldr`); on a symmetric `S` the deposited
`Z`-block is exactly the symmetric bilinear form `k ↦ ∑ₗ S_{k,l} xₗ = x ᵥ* S`
(`phaseCZZ_of_symm`). Transporting
that check-row action through the label bijection `checkVec`/`vecPauli` identifies the network's
`cliffordLabelMap` with the right action `v ↦ v ᵥ* shearZ S`, hence
`cliffordSymplectic (phaseCZNetwork …) = shearZ S` (`cliffordSymplectic_phaseCZNetwork_isSymm`).

## Placement

The statement quantifies over the raw carrier `Matrix … (ZMod 2)`, the `cliffordSymplectic` carrier
accessor, and `shearZ`; this is pure `𝔽₂` linear algebra, so —
like `CliffordSymplecticGeneration.lean`, `CliffordSymplecticLevi.lean` and
`BinarySymplecticGroup.lean`.lean` is a
docstring-only pointer.
-/

open Matrix

namespace CliffordCSS

variable {n : ℕ}

/-- The check row of the Pauli string `vecPauli v` reads off the `X`- and `Z`-halves of the label
`v = (x | z)`: `checkRow (vecPauli v) = (fun k => v (inl k), fun k => v (inr k))`. The split-pair
form of `checkVec_vecPauli` (`checkVec (vecPauli v) = v`), used to feed the label bijection into the
check-row action of a layered circuit. -/
private theorem checkRow_vecPauli (v : Fin n ⊕ Fin n → ZMod 2) :
    checkRow (vecPauli v) = (fun k => v (Sum.inl k), fun k => v (Sum.inr k)) := by
  have h := checkVec_vecPauli v
  rw [checkVec] at h
  ext k
  · exact congrFun h (Sum.inl k)
  · exact congrFun h (Sum.inr k)

/-- **The phase / controlled-`Z` network of a symmetric matrix realizes its `Z`-shear.** For
symmetric `S`, the network `phaseCZNetwork (phaseWires S) (czPairs S)` — a phase gate on each wire
with `S_{k,k} = 1` and a controlled-`Z` on each pair `c < t` with `S_{c,t} = 1` — has symplectic
image exactly the `Z`-shear `U_Z(S) = [[I, S], [0, I]]`.

The proof transports the network's already-computed **check-row** action
(`checkRow_act_phaseCZNetwork` + the closed fold `czCol_foldr`) through the label bijection: writing
a label `v = (x | z)` as `checkVec (vecPauli v)`, the network sends the `X`-part `x` unchanged and
the `Z`-part `z` to `z + phaseCZZ (phaseWires S) (czPairs S) x`, and on a *symmetric* `S` that
deposit is the row `k ↦ ∑ₗ S_{k,l} xₗ = (x ᵥ* S) k` (`phaseCZZ_of_symm`, using `S_{k,l} = S_{l,k}`)
— exactly the `Z`-shear action `(x | z) ↦ (x | x ᵥ* S + z)` (`vecMul_shearZ`). -/
theorem cliffordSymplectic_phaseCZNetwork_isSymm
    (S : Matrix (Fin n) (Fin n) (ZMod 2)) (hS : S.IsSymm) :
    cliffordSymplectic (phaseCZNetwork (phaseWires S) (czPairs S)) = shearZ S := by
  have hsymm : ∀ a b, S a b = S b a := fun a b => hS.apply b a
  refine cliffordSymplectic_eq_of_labelMap (fun v => ?_)
  obtain ⟨x, z, rfl⟩ : ∃ x z, v = Sum.elim x z :=
    ⟨fun k => v (Sum.inl k), fun k => v (Sum.inr k), by ext (k | k) <;> rfl⟩
  rw [cliffordLabelMap_apply, checkVec,
    checkRow_act_phaseCZNetwork _ _ (phaseWires_nodup S) (fun p hp => czPairs_ne hp),
    checkRow_vecPauli]
  simp only [Sum.elim_inl, Sum.elim_inr]
  rw [czCol_foldr, vecMul_shearZ]
  refine congrArg₂ Sum.elim rfl ?_
  funext k
  have hpz := phaseCZZ_of_symm S hsymm x k
  simp only [phaseCZZ] at hpz
  have hvm : (x ᵥ* S) k = ∑ l, S k l * x l := by
    rw [← Matrix.mulVec_transpose, hS]; rfl
  simp only [sCol, Pi.add_apply]
  rw [hvm, ← hpz]
  abel

/-- **Every `Z`-shear is the symplectic image of a phase / controlled-`Z` circuit.** For any
symmetric `S`, some Clifford circuit `U` (a word in the single-wire phase gates and two-wire
controlled-`Z` gates) satisfies `cliffordSymplectic U = shearZ S`, where
`shearZ S = [[I, S], [0, I]]` is the `Z`-shear `U_Z(S)`. Equivalently the `Z`-shear (diagonal)
subgroup of `Sp(2n, 𝔽₂)` is
generated by the phase and controlled-`Z` gates.

The `Z`-part engine of the certificate-route generation result (work item **W1**): the phase/`CZ`
network realizes the full symmetric-matrix-worth of `Z`-shears, the diagonal companion of the Levi
engine's `GL(n, 𝔽₂)`-worth of block-diagonal transformations. The witness is
`phaseCZNetwork (phaseWires S) (czPairs S)` (`cliffordSymplectic_phaseCZNetwork_isSymm`). -/
theorem exists_cliffordSymplectic_eq_shearZ
    (S : Matrix (Fin n) (Fin n) (ZMod 2)) (hS : S.IsSymm) :
    ∃ U : CliffordCircuit n, cliffordSymplectic U = shearZ S :=
  ⟨phaseCZNetwork (phaseWires S) (czPairs S), cliffordSymplectic_phaseCZNetwork_isSymm S hS⟩

end CliffordCSS
