import CliffordCSS.Symplectic.Shear

/-!
# The `X`-shear subgroup is generated by Hadamard-conjugated phase/`CZ` gates

Pure mathematics : every **`X`-shear** `L_X(T) = [[I, 0], [T, I]]`
with `T` symmetric (*Beyond transversality* Convention c7, `shearX`) is the symplectic image of a
**Clifford circuit** — `∃ U : CliffordCircuit n, cliffordSymplectic U = shearX T`
(`exists_cliffordSymplectic_eq_shearX`). Equivalently the `X`-shear subgroup of `Sp(2n, 𝔽₂)`, the
`X ↔ Z` dual of the `Z`-shear (diagonal) subgroup, is generated by the elementary Clifford gates.

This is the **`X`-part shear engine** of the certificate-route generation result (work item **W1**,
`dec-conditional-d1-certificate-route`), the exact dual of the `Z`-shear engine
`exists_cliffordSymplectic_eq_shearZ` (`CliffordCSS/Symplectic/Shear.lean`). The symplectic
Gaussian elimination behind `cliffordSymplectic` surjectivity uses it to clear the *`X`*-part of a
label whose `Z`-part is already placed — the move a `Z`-shear (which fixes the `X`-part) and a Levi
gate (which cannot annihilate a nonzero `X`-part, being invertible) both cannot make. The phase/`CZ`
network only produces `Z`-shears; the `X`-shears are exactly its `X ↔ Z` conjugates.

## The generation, at a glance

The `X`-shear is the `Z`-shear conjugated by the **full `X ↔ Z` swap** `Λ = symplecticMatrix`
(`[[0, I], [I, 0]]`, the Gram matrix of the symplectic form): a direct block computation gives
`Λ · U_Z(T) · Λ = L_X(T)` (`symplecticMatrix_mul_shearZ_mul_symplecticMatrix`). The swap itself is
realized by the **all-wires Hadamard circuit** `hadamardAll` — a Hadamard on every wire — whose
symplectic image is `Λ` (`cliffordSymplectic_hadamardAll`), since each Hadamard exchanges its wire's
`X`- and `Z`-bits (`pauliBit_hadamardPauli`) and the wires are distinct
(`List.nodup_finRange`). Sandwiching the phase/`CZ` circuit of the `Z`-shear engine between two
copies of `hadamardAll` therefore realizes `L_X(T)` by functoriality (`cliffordSymplectic_append`).

## Placement

The statement quantifies over the raw carrier `Matrix … (ZMod 2)`, the `cliffordSymplectic` carrier
accessor, and `shearX`; this is pure `𝔽₂` linear algebra, so —
like `CliffordSymplecticShear.lean`, `CliffordSymplecticLevi.lean` and
`CliffordSymplecticGeneration.lean`.lean`
is a docstring-only pointer.
-/

open Matrix

namespace CliffordCSS

variable {n : ℕ}

/-! ### The all-wires Hadamard circuit realizes the `X ↔ Z` swap `Λ` -/

/-- The **all-wires Hadamard circuit** `H^{⊗n}`: the Hadamard layer `hadLayer` on every wire,
`[had 0, …, had (n-1)]`. Its symplectic image is the full `X ↔ Z` swap `Λ = symplecticMatrix`
(`cliffordSymplectic_hadamardAll`). -/
def hadamardAll (n : ℕ) : CliffordCircuit n := hadLayer (List.finRange n)

/-- On every wire the all-Hadamards circuit applies the single-qubit Hadamard tableau:
`(hadamardAll n).act g k = hadamardPauli (g k)`. Every wire is in `List.finRange n` exactly once, so
this is the Hadamard-layer row action `act_hadLayer` at the full (nodup) wire list. -/
private theorem hadamardAll_act_apply (g : Fin n → Fin 4) (k : Fin n) :
    CliffordCircuit.act (hadamardAll n) g k = hadamardPauli (g k) := by
  rw [hadamardAll, congrFun (act_hadLayer (List.finRange n) g (List.nodup_finRange n)) k,
    if_pos (List.mem_finRange k)]

/-- **The all-wires Hadamard circuit realizes the `X ↔ Z` swap** `Λ = symplecticMatrix`:
`cliffordSymplectic (hadamardAll n) = symplecticMatrix`. On a label `(x | z)` the circuit exchanges
the two halves, `(x | z) ↦ (z | x)`: each Hadamard swaps its wire's `X`- and `Z`-bits
(`pauliBit_hadamardPauli` through `hadamardAll_act_apply`), and `Λ`'s right action is exactly that
block swap (`vecMul_fromBlocks_blocks`). This is the symplectic form of "Hadamard interchanges the
computational and Hadamard bases": `Λ` is the Gram matrix of the very form the Clifford action
preserves. -/
theorem cliffordSymplectic_hadamardAll :
    cliffordSymplectic (hadamardAll n) = symplecticMatrix := by
  refine cliffordSymplectic_eq_of_labelMap (fun v => ?_)
  obtain ⟨x, z, rfl⟩ : ∃ x z, v = Sum.elim x z :=
    ⟨fun k => v (Sum.inl k), fun k => v (Sum.inr k), by ext (k | k) <;> rfl⟩
  have hlabel : cliffordLabelMap (hadamardAll n) (Sum.elim x z) = Sum.elim z x := by
    refine cliffordLabelMap_eq_of_pauliBit fun k => ?_
    rw [hadamardAll_act_apply, pauliBit_hadamardPauli]
    simp [vecPauli, pauliBit_bitToPauli]
  rw [hlabel, symplecticMatrix, vecMul_fromBlocks_blocks]
  simp

/-! ### Every `X`-shear is a Hadamard-conjugated `Z`-shear -/

/-- **Conjugating a `Z`-shear by the swap `Λ` gives the dual `X`-shear:**
`Λ · U_Z(T) · Λ = L_X(T)`. A direct block computation:
`[[0, I], [I, 0]] · [[I, T], [0, I]] · [[0, I], [I, 0]] = [[I, 0], [T, I]]`. No symmetry of `T` is
needed for this matrix identity (symmetry is used only to realize `U_Z(T)` by a circuit). -/
theorem symplecticMatrix_mul_shearZ_mul_symplecticMatrix (T : Matrix (Fin n) (Fin n) (ZMod 2)) :
    (symplecticMatrix * shearZ T : Matrix (Fin n ⊕ Fin n) (Fin n ⊕ Fin n) (ZMod 2))
        * symplecticMatrix = shearX T := by
  rw [symplecticMatrix, shearZ, shearX, Matrix.fromBlocks_multiply, Matrix.fromBlocks_multiply]
  simp only [Matrix.mul_zero, Matrix.zero_mul, Matrix.mul_one, Matrix.one_mul, add_zero, zero_add]

/-- **Every `X`-shear is the symplectic image of a Clifford circuit.** For any symmetric `T`, some
Clifford circuit `U` — the phase/`CZ` network realizing `U_Z(T)` sandwiched between two all-wires
Hadamard layers — satisfies `cliffordSymplectic U = shearX T`, where `shearX T = [[I, 0], [T, I]]`
is the `X`-shear `L_X(T)`. Equivalently the `X`-shear subgroup of `Sp(2n, 𝔽₂)` is generated by the
elementary Clifford gates.

The `X`-part shear engine of the certificate-route generation result (work item **W1**), the
`X ↔ Z` dual of the `Z`-shear engine `exists_cliffordSymplectic_eq_shearZ`. Proof: conjugate the
`Z`-shear circuit `V` for `T` (`exists_cliffordSymplectic_eq_shearZ`, valid as `T` is symmetric) by
the all-wires Hadamard circuit; `cliffordSymplectic (hadamardAll ++ V ++ hadamardAll)
= Λ · U_Z(T) · Λ = L_X(T)` by functoriality (`cliffordSymplectic_append`),
`cliffordSymplectic_hadamardAll`, and `symplecticMatrix_mul_shearZ_mul_symplecticMatrix`. -/
theorem exists_cliffordSymplectic_eq_shearX (T : Matrix (Fin n) (Fin n) (ZMod 2)) (hT : T.IsSymm) :
    ∃ U : CliffordCircuit n, cliffordSymplectic U = shearX T := by
  obtain ⟨V, hV⟩ := exists_cliffordSymplectic_eq_shearZ T hT
  refine ⟨hadamardAll n ++ V ++ hadamardAll n, ?_⟩
  rw [cliffordSymplectic_append, cliffordSymplectic_append, cliffordSymplectic_hadamardAll, hV,
    ← mul_assoc, symplecticMatrix_mul_shearZ_mul_symplecticMatrix]

end CliffordCSS
